// satzbau_data.js — Curriculum for the Satzbau Lab game (word order, A1 → B2)
//
// Level: { id, label, cefr, color, rule: {headline, diagram[], points[], examples[], contrast?}, items[] }
//
// Item types:
//   order — { id, type:"order", en, parts:[{text,pos,label?}], why }   parts array order IS the answer
//   conj  — { id, type:"conj", clauseA, clauseB, answer, options:[{word,effect,result,note}], why }
//           effect: "end" (verb to the end) | "pos0" (nothing moves) | "pos1" (connector takes slot 1)
//   fix   — { id, type:"fix", wrong, correct, badIndex, why }          badIndex = token index in `wrong`
//
// `pos` values reuse the .satz-part colour keys in style.css:
//   verb subj frage conj temp manner local erg dativ akk

const SATZBAU_LEVELS = [

  // ---------------------------------------------------------------- 1. V2
  {
    id: "v2",
    label: "Position 2 — die Grundregel",
    cefr: "A1",
    color: "#4a9eff",
    rule: {
      headline: "In a German statement the conjugated verb is ALWAYS the second element.",
      diagram: [
        { text: "Ich",     label: "Pos 1",  pos: "subj" },
        { text: "lerne",   label: "Pos 2 — VERB", pos: "verb" },
        { text: "heute",   label: "Pos 3",  pos: "temp" },
        { text: "Deutsch.", label: "Rest",  pos: "erg" },
      ],
      points: [
        "\"Second element\" means second <em>chunk</em>, not second word — \"Meine kleine Schwester\" is one element.",
        "The subject is the most common position 1, but it does not have to be there.",
        "Only ONE element may stand in front of the verb. Two is always wrong.",
      ],
      examples: [
        { de: "Ich lerne jeden Tag Deutsch.", en: "I learn German every day." },
        { de: "Meine Schwester wohnt in Bremen.", en: "My sister lives in Bremen." },
        { de: "Der Kurs beginnt um neun Uhr.", en: "The course starts at nine." },
      ],
      contrast: {
        a: "Ich lerne heute Deutsch.",
        b: "Heute lerne ich Deutsch.",
        note: "Different position 1 — but the verb is element 2 in both.",
      },
    },
    items: [
      { id: 1101, type: "order", en: "I learn German every day.",
        parts: [ {text:"Ich",pos:"subj",label:"Pos 1"}, {text:"lerne",pos:"verb",label:"Pos 2"}, {text:"jeden Tag",pos:"temp"}, {text:"Deutsch.",pos:"erg"} ],
        why: "The conjugated verb <em>lerne</em> is element 2 — nothing may push it out of that slot." },
      { id: 1102, type: "order", en: "My sister lives in Bremen.",
        parts: [ {text:"Meine Schwester",pos:"subj",label:"Pos 1"}, {text:"wohnt",pos:"verb",label:"Pos 2"}, {text:"in Bremen.",pos:"local"} ],
        why: "\"Meine Schwester\" is a single element, so <em>wohnt</em> is still element 2." },
      { id: 1103, type: "order", en: "We drink coffee in the morning.",
        parts: [ {text:"Wir",pos:"subj",label:"Pos 1"}, {text:"trinken",pos:"verb",label:"Pos 2"}, {text:"am Morgen",pos:"temp"}, {text:"Kaffee.",pos:"akk"} ],
        why: "Verb second, then time, then the object." },
      { id: 1104, type: "order", en: "The course starts at nine o'clock.",
        parts: [ {text:"Der Kurs",pos:"subj",label:"Pos 1"}, {text:"beginnt",pos:"verb",label:"Pos 2"}, {text:"um neun Uhr.",pos:"temp"} ],
        why: "Subject on 1, conjugated verb on 2." },
      { id: 1105, type: "fix", wrong: "Ich jeden Tag lerne Deutsch.", correct: "Ich lerne jeden Tag Deutsch.", badIndex: 3,
        why: "<em>lerne</em> must be element 2 — \"jeden Tag\" cannot stand between the subject and the verb." },
      { id: 1106, type: "fix", wrong: "Meine Familie in Hamburg wohnt.", correct: "Meine Familie wohnt in Hamburg.", badIndex: 4,
        why: "German is not verb-final in a main clause — <em>wohnt</em> belongs in slot 2." },
      { id: 1107, type: "order", en: "I play table tennis on Sundays.",
        parts: [ {text:"Ich",pos:"subj",label:"Pos 1"}, {text:"spiele",pos:"verb",label:"Pos 2"}, {text:"am Sonntag",pos:"temp"}, {text:"Tischtennis.",pos:"akk"} ],
        why: "Verb second; time before the object." },
      { id: 1108, type: "fix", wrong: "Am Wochenende ich arbeite im Café.", correct: "Am Wochenende arbeite ich im Café.", badIndex: 3,
        why: "\"Am Wochenende\" already fills position 1, so the verb must come next and the subject slides behind it." },
      { id: 1109, type: "order", en: "He buys bread at the supermarket.",
        parts: [ {text:"Er",pos:"subj",label:"Pos 1"}, {text:"kauft",pos:"verb",label:"Pos 2"}, {text:"im Supermarkt",pos:"local"}, {text:"Brot.",pos:"akk"} ],
        why: "Verb second — everything else follows." },
      { id: 1110, type: "order", en: "The exam lasts three hours.",
        parts: [ {text:"Die Prüfung",pos:"subj",label:"Pos 1"}, {text:"dauert",pos:"verb",label:"Pos 2"}, {text:"drei Stunden.",pos:"temp"} ],
        why: "Subject, verb, rest." },
      { id: 1111, type: "fix", wrong: "Der Bus um acht Uhr fährt.", correct: "Der Bus fährt um acht Uhr.", badIndex: 5,
        why: "<em>fährt</em> is the conjugated verb of a main clause — element 2, never the end." },
      { id: 1112, type: "order", en: "I need a certificate for the application.",
        parts: [ {text:"Ich",pos:"subj",label:"Pos 1"}, {text:"brauche",pos:"verb",label:"Pos 2"}, {text:"für die Bewerbung",pos:"erg"}, {text:"ein Zertifikat.",pos:"akk"} ],
        why: "Verb second, then the rest of the sentence." },
    ],
  },

  // ---------------------------------------------------------- 2. Inversion
  {
    id: "inversion",
    label: "Inversion — etwas anderes auf Position 1",
    cefr: "A1",
    color: "#22d3ee",
    rule: {
      headline: "Put anything else in position 1 and the subject moves behind the verb. The verb never moves.",
      diagram: [
        { text: "Heute",    label: "Pos 1 — Zeit", pos: "temp" },
        { text: "lerne",    label: "Pos 2 — VERB", pos: "verb" },
        { text: "ich",      label: "Subjekt",      pos: "subj" },
        { text: "Deutsch.", label: "Rest",         pos: "erg" },
      ],
      points: [
        "Position 1 can be a time, a place, an object, a whole subordinate clause — anything.",
        "Fronting an element is how you signal what the sentence is <em>about</em>.",
        "There is never a subject AND another element before the verb.",
      ],
      examples: [
        { de: "Heute Abend tanze ich Bachata.", en: "This evening I dance bachata." },
        { de: "In Bremen gibt es viele Sprachcafés.", en: "In Bremen there are many language cafés." },
        { de: "Diesen Text verstehe ich nicht.", en: "This text I do not understand." },
      ],
      contrast: {
        a: "Ich lerne heute Deutsch.",
        b: "Heute lerne ich Deutsch.",
        note: "Fronting \"heute\" pushes \"ich\" behind the verb — that swap is the inversion.",
      },
    },
    items: [
      { id: 1201, type: "order", en: "This evening I dance bachata.",
        parts: [ {text:"Heute Abend",pos:"temp",label:"Pos 1"}, {text:"tanze",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"Bachata.",pos:"akk"} ],
        why: "Time on position 1 → verb stays second → subject behind it." },
      { id: 1202, type: "order", en: "In Bremen there are many language cafés.",
        parts: [ {text:"In Bremen",pos:"local",label:"Pos 1"}, {text:"gibt",pos:"verb",label:"Pos 2"}, {text:"es",pos:"subj"}, {text:"viele Sprachcafés.",pos:"akk"} ],
        why: "Place first, verb second, the dummy subject <em>es</em> behind it." },
      { id: 1203, type: "order", en: "Since my graduation I learn German daily.",
        parts: [ {text:"Seit meinem Abschluss",pos:"temp",label:"Pos 1"}, {text:"lerne",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"täglich Deutsch.",pos:"erg"} ],
        why: "A four-word time phrase is still ONE element." },
      { id: 1204, type: "fix", wrong: "Nach dem Kurs ich gehe einkaufen.", correct: "Nach dem Kurs gehe ich einkaufen.", badIndex: 4,
        why: "\"Nach dem Kurs\" occupies position 1, so <em>gehe</em> comes next and <em>ich</em> follows it." },
      { id: 1205, type: "order", en: "Twice a week I play table tennis.",
        parts: [ {text:"Zweimal pro Woche",pos:"temp",label:"Pos 1"}, {text:"spiele",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"Tischtennis.",pos:"akk"} ],
        why: "Frequency phrase on 1, verb on 2." },
      { id: 1206, type: "fix", wrong: "Morgen ich schreibe meine Bewerbung.", correct: "Morgen schreibe ich meine Bewerbung.", badIndex: 2,
        why: "Two elements before the verb is always wrong — <em>schreibe</em> must be second." },
      { id: 1207, type: "order", en: "On the tennis court I often meet new people.",
        parts: [ {text:"Auf dem Tennisplatz",pos:"local",label:"Pos 1"}, {text:"treffe",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"oft neue Leute.",pos:"erg"} ],
        why: "Place on 1 → inversion." },
      { id: 1208, type: "order", en: "For my master's application I need a B2 certificate.",
        parts: [ {text:"Für meine Masterbewerbung",pos:"erg",label:"Pos 1"}, {text:"brauche",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"ein B2-Zertifikat.",pos:"akk"} ],
        why: "A purpose phrase can hold position 1 just as well." },
      { id: 1209, type: "fix", wrong: "Im Sommer wir fahren nach Italien.", correct: "Im Sommer fahren wir nach Italien.", badIndex: 3,
        why: "\"Im Sommer\" is position 1 — the verb must follow immediately." },
      { id: 1210, type: "order", en: "At the station I wait for my friend.",
        parts: [ {text:"Am Bahnhof",pos:"local",label:"Pos 1"}, {text:"warte",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"auf meinen Freund.",pos:"erg"} ],
        why: "Verb second, subject third." },
      { id: 1211, type: "order", en: "This text I do not understand.",
        parts: [ {text:"Diesen Text",pos:"akk",label:"Pos 1"}, {text:"verstehe",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"nicht.",pos:"erg"} ],
        why: "Even the accusative object can be fronted for emphasis — the verb still holds slot 2." },
      { id: 1212, type: "fix", wrong: "Leider ich habe keine Zeit.", correct: "Leider habe ich keine Zeit.", badIndex: 2,
        why: "<em>Leider</em> fills position 1, so <em>habe</em> is next." },
    ],
  },

  // ------------------------------------------------------------- 3. Fragen
  {
    id: "fragen",
    label: "Fragen — W-Frage und Ja/Nein-Frage",
    cefr: "A1",
    color: "#f59e0b",
    rule: {
      headline: "W-Frage: W-Wort + Verb + Subjekt. Ja/Nein-Frage: Verb + Subjekt — nothing in front.",
      diagram: [
        { text: "Wann",      label: "Pos 1 — W-Wort", pos: "frage" },
        { text: "beginnt",   label: "Pos 2 — VERB",   pos: "verb" },
        { text: "der Kurs?", label: "Subjekt",        pos: "subj" },
      ],
      points: [
        "The W-word simply occupies position 1 — so the verb-second rule is unchanged.",
        "A yes/no question leaves position 1 empty, so the verb starts the sentence.",
        "Never squeeze the subject between the W-word and the verb.",
      ],
      examples: [
        { de: "Was brauchst du für ein Masterstudium?", en: "What do you need for a master's?" },
        { de: "Wie lange dauert der B2-Kurs?", en: "How long does the B2 course take?" },
        { de: "Kommst du aus den USA?", en: "Are you from the States?" },
      ],
      contrast: {
        a: "Wann beginnt der Kurs?",
        b: "Beginnt der Kurs um neun?",
        note: "Drop the W-word and the verb slides into position 1.",
      },
    },
    items: [
      { id: 1301, type: "order", en: "When does the course start?",
        parts: [ {text:"Wann",pos:"frage",label:"Pos 1"}, {text:"beginnt",pos:"verb",label:"Pos 2"}, {text:"der Kurs?",pos:"subj"} ],
        why: "W-Wort, Verb, Subjekt." },
      { id: 1302, type: "order", en: "What do you need for a master's degree?",
        parts: [ {text:"Was",pos:"frage",label:"Pos 1"}, {text:"brauchst",pos:"verb",label:"Pos 2"}, {text:"du",pos:"subj"}, {text:"für ein Masterstudium?",pos:"erg"} ],
        why: "The W-word holds position 1, so the verb is still element 2." },
      { id: 1303, type: "order", en: "Do you learn German too?",
        parts: [ {text:"Lernst",pos:"verb",label:"Pos 1 — VERB"}, {text:"du",pos:"subj"}, {text:"auch Deutsch?",pos:"erg"} ],
        why: "Ja/Nein-Frage: no position 1 filler, so the verb comes first." },
      { id: 1304, type: "order", en: "How long does the course take?",
        parts: [ {text:"Wie lange",pos:"frage",label:"Pos 1"}, {text:"dauert",pos:"verb",label:"Pos 2"}, {text:"der Kurs?",pos:"subj"} ],
        why: "\"Wie lange\" is one question element." },
      { id: 1305, type: "fix", wrong: "Warum du lernst Deutsch?", correct: "Warum lernst du Deutsch?", badIndex: 2,
        why: "The subject never stands between the W-word and the verb." },
      { id: 1306, type: "order", en: "Where can I practise German here?",
        parts: [ {text:"Wo",pos:"frage",label:"Pos 1"}, {text:"kann",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"hier Deutsch üben?",pos:"erg"} ],
        why: "The conjugated modal <em>kann</em> takes slot 2; the infinitive closes the sentence." },
      { id: 1307, type: "order", en: "Are you from the States?",
        parts: [ {text:"Kommst",pos:"verb",label:"Pos 1 — VERB"}, {text:"du",pos:"subj"}, {text:"aus den USA?",pos:"local"} ],
        why: "Yes/no question — verb first." },
      { id: 1308, type: "fix", wrong: "Wie viel der Kurs kostet?", correct: "Wie viel kostet der Kurs?", badIndex: 4,
        why: "A question is a main clause — the verb is element 2, not final." },
      { id: 1309, type: "order", en: "Do you have time today?",
        parts: [ {text:"Hast",pos:"verb",label:"Pos 1 — VERB"}, {text:"du",pos:"subj"}, {text:"heute Zeit?",pos:"erg"} ],
        why: "Verb, subject, rest." },
      { id: 1310, type: "order", en: "Why are you learning German?",
        parts: [ {text:"Warum",pos:"frage",label:"Pos 1"}, {text:"lernst",pos:"verb",label:"Pos 2"}, {text:"du",pos:"subj"}, {text:"Deutsch?",pos:"akk"} ],
        why: "W-Wort, Verb, Subjekt, Rest." },
      { id: 1311, type: "fix", wrong: "Gibt in Bremen es einen Bachata-Kurs?", correct: "Gibt es in Bremen einen Bachata-Kurs?", badIndex: 3,
        why: "In a yes/no question the subject comes straight after the verb." },
      { id: 1312, type: "order", en: "Who do you talk to at the language café?",
        parts: [ {text:"Mit wem",pos:"frage",label:"Pos 1"}, {text:"sprichst",pos:"verb",label:"Pos 2"}, {text:"du",pos:"subj"}, {text:"am Sprachcafé?",pos:"local"} ],
        why: "The preposition travels with the question word into position 1." },
    ],
  },

  // ----------------------------------------------------------- 4. Klammer
  {
    id: "klammer",
    label: "Satzklammer — zweiter Verbteil ans Ende",
    cefr: "A2",
    color: "#fb923c",
    rule: {
      headline: "Two verb parts form a bracket: the conjugated one at position 2, the other at the very end.",
      diagram: [
        { text: "Ich",           label: "Pos 1", pos: "subj" },
        { text: "muss",          label: "Pos 2 — konjugiert", pos: "verb" },
        { text: "heute",         label: "Mittelfeld", pos: "temp" },
        { text: "die Bewerbung", label: "Mittelfeld", pos: "akk" },
        { text: "abschicken.",   label: "Ende — Infinitiv", pos: "verb" },
      ],
      points: [
        "Modal + Infinitiv, Perfekt (haben/sein + Partizip II), Futur (werden + Infinitiv) — same bracket.",
        "Separable verbs split: the prefix flies to the end (<em>ich rufe dich an</em>).",
        "Everything else lives <em>inside</em> the bracket — that space is the Mittelfeld.",
      ],
      examples: [
        { de: "Ich muss heute die Bewerbung abschicken.", en: "I have to send the application today." },
        { de: "Wir haben gestern im Sprachcafé gesprochen.", en: "We talked at the language café yesterday." },
        { de: "Ich stehe jeden Morgen um sechs Uhr auf.", en: "I get up at six every morning." },
      ],
      contrast: {
        a: "Ich rufe dich später an.",
        b: "Ich habe dich später angerufen.",
        note: "Separable prefix or Partizip II — either way the bracket closes at the end.",
      },
    },
    items: [
      { id: 1401, type: "order", en: "I have to send the application today.",
        parts: [ {text:"Ich",pos:"subj",label:"Pos 1"}, {text:"muss",pos:"verb",label:"Pos 2"}, {text:"heute",pos:"temp"}, {text:"die Bewerbung",pos:"akk"}, {text:"abschicken.",pos:"verb",label:"Ende"} ],
        why: "The modal is conjugated at slot 2; the infinitive closes the bracket." },
      { id: 1402, type: "order", en: "We talked at the language café yesterday.",
        parts: [ {text:"Wir",pos:"subj",label:"Pos 1"}, {text:"haben",pos:"verb",label:"Pos 2"}, {text:"gestern",pos:"temp"}, {text:"im Sprachcafé",pos:"local"}, {text:"gesprochen.",pos:"verb",label:"Ende"} ],
        why: "Perfekt: <em>haben</em> at 2, Partizip II at the end." },
      { id: 1403, type: "order", en: "I'll call you later.",
        parts: [ {text:"Ich",pos:"subj",label:"Pos 1"}, {text:"rufe",pos:"verb",label:"Pos 2"}, {text:"dich",pos:"akk"}, {text:"später",pos:"temp"}, {text:"an.",pos:"verb",label:"Präfix"} ],
        why: "<em>anrufen</em> splits — the prefix <em>an</em> closes the sentence." },
      { id: 1404, type: "fix", wrong: "Ich habe angerufen dich gestern.", correct: "Ich habe dich gestern angerufen.", badIndex: 2,
        why: "The Partizip II closes the bracket — it cannot sit next to <em>habe</em>." },
      { id: 1405, type: "order", en: "She wants to study in Germany next year.",
        parts: [ {text:"Sie",pos:"subj",label:"Pos 1"}, {text:"will",pos:"verb",label:"Pos 2"}, {text:"nächstes Jahr",pos:"temp"}, {text:"in Deutschland",pos:"local"}, {text:"studieren.",pos:"verb",label:"Ende"} ],
        why: "Modal at 2, infinitive at the end, everything else in between." },
      { id: 1406, type: "order", en: "The course started two weeks ago.",
        parts: [ {text:"Der Kurs",pos:"subj",label:"Pos 1"}, {text:"hat",pos:"verb",label:"Pos 2"}, {text:"vor zwei Wochen",pos:"temp"}, {text:"angefangen.",pos:"verb",label:"Ende"} ],
        why: "Perfekt bracket: <em>hat … angefangen</em>." },
      { id: 1407, type: "fix", wrong: "Ich kann abholen dich am Bahnhof.", correct: "Ich kann dich am Bahnhof abholen.", badIndex: 2,
        why: "The infinitive belongs at the end, after the object and the place." },
      { id: 1408, type: "order", en: "We will go to Italy in the summer.",
        parts: [ {text:"Wir",pos:"subj",label:"Pos 1"}, {text:"werden",pos:"verb",label:"Pos 2"}, {text:"im Sommer",pos:"temp"}, {text:"nach Italien",pos:"local"}, {text:"fahren.",pos:"verb",label:"Ende"} ],
        why: "Futur I is a bracket too: <em>werden … fahren</em>." },
      { id: 1409, type: "order", en: "I get up at six every morning.",
        parts: [ {text:"Ich",pos:"subj",label:"Pos 1"}, {text:"stehe",pos:"verb",label:"Pos 2"}, {text:"jeden Morgen",pos:"temp"}, {text:"um sechs Uhr",pos:"temp"}, {text:"auf.",pos:"verb",label:"Präfix"} ],
        why: "<em>aufstehen</em> splits; <em>auf</em> is the last word." },
      { id: 1410, type: "fix", wrong: "Sie hat gekauft ein neues Fahrrad.", correct: "Sie hat ein neues Fahrrad gekauft.", badIndex: 2,
        why: "The object goes inside the bracket, the Partizip II closes it." },
      { id: 1411, type: "order", en: "You may not park here.",
        parts: [ {text:"Du",pos:"subj",label:"Pos 1"}, {text:"darfst",pos:"verb",label:"Pos 2"}, {text:"hier",pos:"local"}, {text:"nicht",pos:"erg"}, {text:"parken.",pos:"verb",label:"Ende"} ],
        why: "<em>nicht</em> sits just before the closing verb part." },
      { id: 1412, type: "order", en: "I would like to watch a film tonight.",
        parts: [ {text:"Ich",pos:"subj",label:"Pos 1"}, {text:"möchte",pos:"verb",label:"Pos 2"}, {text:"heute Abend",pos:"temp"}, {text:"einen Film",pos:"akk"}, {text:"sehen.",pos:"verb",label:"Ende"} ],
        why: "Modal bracket with time before object." },
    ],
  },

  // -------------------------------------------------------------- 5. Pos 0
  {
    id: "pos0",
    label: "Position 0 — und, aber, denn, oder, sondern",
    cefr: "B1",
    color: "#6b7280",
    rule: {
      headline: "These conjunctions sit OUTSIDE the count. Nothing moves — the clause after them is fully normal.",
      diagram: [
        { text: "Deutsch ist schwer,", label: "Hauptsatz", pos: "erg" },
        { text: "aber",                label: "Position 0", pos: "conj" },
        { text: "es",                  label: "Pos 1",      pos: "subj" },
        { text: "macht",               label: "Pos 2 — VERB", pos: "verb" },
        { text: "Spaß.",               label: "Rest",       pos: "erg" },
      ],
      points: [
        "und · aber · oder · denn · sondern · doch — six words, zero effect on word order.",
        "<em>denn</em> means \"because\", exactly like <em>weil</em>, but it does NOT send the verb to the end.",
        "<em>sondern</em> only ever follows a negation (nicht … sondern).",
      ],
      examples: [
        { de: "Ich lerne Deutsch, denn ich wohne in Deutschland.", en: "I learn German because I live in Germany." },
        { de: "Sie arbeitet in Hamburg, aber sie wohnt in Bremen.", en: "She works in Hamburg but lives in Bremen." },
        { de: "Er kommt nicht aus Berlin, sondern aus Bremen.", en: "He is not from Berlin but from Bremen." },
      ],
      contrast: {
        a: "Ich lerne Deutsch, denn ich wohne in Deutschland.",
        b: "Ich lerne Deutsch, weil ich in Deutschland wohne.",
        note: "Same meaning. denn = position 0 (nothing moves), weil = verb to the end.",
      },
    },
    items: [
      { id: 1501, type: "conj", clauseA: "Deutsch ist schwer", clauseB: "Es macht mir Spaß", answer: "aber",
        options: [
          { word:"aber", effect:"pos0", result:"Deutsch ist schwer, aber es macht mir Spaß.", note:"Position 0 — the second clause keeps completely normal V2 order." },
          { word:"obwohl", effect:"end", result:"Deutsch ist schwer, obwohl es mir Spaß macht.", note:"Subordinating — macht goes to the end. Grammatical, but it twists the logic." },
          { word:"trotzdem", effect:"pos1", result:"Deutsch ist schwer, trotzdem macht es mir Spaß.", note:"Takes position 1 — macht stays at 2 and es moves behind it." },
          { word:"deshalb", effect:"pos1", result:"Deutsch ist schwer, deshalb macht es mir Spaß.", note:"Position 1 connector, but \"that's why\" is the wrong link here." },
        ],
        why: "<em>aber</em> is a position-0 conjunction: it joins two main clauses and changes nothing." },
      { id: 1502, type: "conj", clauseA: "Ich lerne Deutsch", clauseB: "Ich wohne in Deutschland", answer: "denn",
        options: [
          { word:"denn", effect:"pos0", result:"Ich lerne Deutsch, denn ich wohne in Deutschland.", note:"Position 0 — wohne stays in slot 2." },
          { word:"weil", effect:"end", result:"Ich lerne Deutsch, weil ich in Deutschland wohne.", note:"Same meaning, but weil kicks wohne to the very end." },
          { word:"deshalb", effect:"pos1", result:"Ich wohne in Deutschland, deshalb lerne ich Deutsch.", note:"Position 1 — the verb stays at 2 and the subject follows it." },
          { word:"und", effect:"pos0", result:"Ich lerne Deutsch und ich wohne in Deutschland.", note:"Position 0 too, but \"and\" throws away the causal link." },
        ],
        why: "<em>denn</em> means \"because\" but sits at position 0 — the verb <em>wohne</em> keeps slot 2." },
      { id: 1503, type: "order", en: "I go to the language café and I meet friends there.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"gehe",pos:"verb",label:"Pos 2"}, {text:"ins Sprachcafé",pos:"local"}, {text:"und",pos:"conj",label:"Position 0"}, {text:"ich",pos:"subj",label:"Pos 1"}, {text:"treffe",pos:"verb",label:"Pos 2"}, {text:"dort Freunde.",pos:"erg"} ],
        why: "<em>und</em> is invisible to the count — the second clause restarts with subject + verb." },
      { id: 1504, type: "fix", wrong: "Ich lerne Deutsch, denn ich in Deutschland wohne.", correct: "Ich lerne Deutsch, denn ich wohne in Deutschland.", badIndex: 7,
        why: "<em>denn</em> is position 0, not subordinating — <em>wohne</em> stays at slot 2." },
      { id: 1505, type: "conj", clauseA: "Er kommt nicht aus Berlin", clauseB: "Er kommt aus Bremen", answer: "sondern",
        options: [
          { word:"sondern", effect:"pos0", result:"Er kommt nicht aus Berlin, sondern aus Bremen.", note:"The correcting \"but\" after a negation — position 0." },
          { word:"aber", effect:"pos0", result:"Er kommt nicht aus Berlin, aber er kommt aus Bremen.", note:"Also position 0, but after a negation German wants sondern." },
          { word:"oder", effect:"pos0", result:"Er kommt nicht aus Berlin oder aus Bremen.", note:"Position 0, but \"or\" changes the meaning entirely." },
          { word:"weil", effect:"end", result:"Er kommt nicht aus Berlin, weil er aus Bremen kommt.", note:"Verb-final — and the logic is now causal, not corrective." },
        ],
        why: "After a negation the correcting \"but\" is <em>sondern</em>. Both it and <em>aber</em> are position 0." },
      { id: 1506, type: "order", en: "We can go to the cinema or we stay at home.",
        parts: [ {text:"Wir",pos:"subj"}, {text:"können",pos:"verb",label:"Pos 2"}, {text:"ins Kino gehen",pos:"erg"}, {text:"oder",pos:"conj",label:"Position 0"}, {text:"wir",pos:"subj",label:"Pos 1"}, {text:"bleiben",pos:"verb",label:"Pos 2"}, {text:"zu Hause.",pos:"local"} ],
        why: "<em>oder</em> costs no slot — the second clause starts fresh." },
      { id: 1507, type: "fix", wrong: "Der Kurs ist teuer, aber lohnt er sich.", correct: "Der Kurs ist teuer, aber er lohnt sich.", badIndex: 6,
        why: "<em>aber</em> does not trigger inversion — subject first, then the verb." },
      { id: 1508, type: "conj", clauseA: "Ich habe die Prüfung bestanden", clauseB: "Ich habe viel gelernt", answer: "denn",
        options: [
          { word:"denn", effect:"pos0", result:"Ich habe die Prüfung bestanden, denn ich habe viel gelernt.", note:"Position 0 — normal order follows." },
          { word:"weil", effect:"end", result:"Ich habe die Prüfung bestanden, weil ich viel gelernt habe.", note:"Verb-final: the conjugated habe lands last." },
          { word:"trotzdem", effect:"pos1", result:"Ich habe viel gelernt, trotzdem habe ich die Prüfung nicht bestanden.", note:"Position 1 — and the meaning flips to concessive." },
          { word:"aber", effect:"pos0", result:"Ich habe die Prüfung bestanden, aber ich habe viel gelernt.", note:"Position 0, but \"but\" makes no sense here." },
        ],
        why: "<em>denn</em> gives the reason without touching the word order." },
      { id: 1509, type: "order", en: "She works in Hamburg but she lives in Bremen.",
        parts: [ {text:"Sie",pos:"subj"}, {text:"arbeitet",pos:"verb",label:"Pos 2"}, {text:"in Hamburg,",pos:"local"}, {text:"aber",pos:"conj",label:"Position 0"}, {text:"sie",pos:"subj",label:"Pos 1"}, {text:"wohnt",pos:"verb",label:"Pos 2"}, {text:"in Bremen.",pos:"local"} ],
        why: "Two full main clauses joined at position 0." },
      { id: 1510, type: "fix", wrong: "Ich möchte kommen, aber habe ich keine Zeit.", correct: "Ich möchte kommen, aber ich habe keine Zeit.", badIndex: 5,
        why: "No inversion after <em>aber</em> — it is not an element of the clause." },
      { id: 1511, type: "conj", clauseA: "Das Zimmer ist klein", clauseB: "Es ist sehr hell", answer: "aber",
        options: [
          { word:"aber", effect:"pos0", result:"Das Zimmer ist klein, aber es ist sehr hell.", note:"Position 0 — plain contrast." },
          { word:"denn", effect:"pos0", result:"Das Zimmer ist klein, denn es ist sehr hell.", note:"Position 0 too, but the causal link is nonsense here." },
          { word:"obwohl", effect:"end", result:"Das Zimmer ist klein, obwohl es sehr hell ist.", note:"Verb-final — ist moves to the end." },
          { word:"deshalb", effect:"pos1", result:"Das Zimmer ist klein, deshalb ist es sehr hell.", note:"Position 1 — verb second, subject behind it." },
        ],
        why: "Plain contrast between two main clauses = <em>aber</em>, position 0." },
      { id: 1512, type: "order", en: "I get up early because the course starts at eight.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"stehe",pos:"verb",label:"Pos 2"}, {text:"früh auf,",pos:"erg"}, {text:"denn",pos:"conj",label:"Position 0"}, {text:"der Kurs",pos:"subj",label:"Pos 1"}, {text:"beginnt",pos:"verb",label:"Pos 2"}, {text:"um acht.",pos:"temp"} ],
        why: "<em>denn</em> leaves the following clause completely untouched." },
    ],
  },

  // -------------------------------------------------------------- 6. Pos 1
  {
    id: "pos1",
    label: "Position 1 — deshalb, trotzdem, dann",
    cefr: "B1",
    color: "#d97706",
    rule: {
      headline: "These connectors ARE position 1. So the verb still comes second — and the subject is pushed behind it.",
      diagram: [
        { text: "Ich wohne hier,", label: "Hauptsatz", pos: "erg" },
        { text: "deshalb",         label: "Position 1", pos: "conj" },
        { text: "lerne",           label: "Pos 2 — VERB", pos: "verb" },
        { text: "ich",             label: "Subjekt",   pos: "subj" },
        { text: "Deutsch.",        label: "Rest",      pos: "erg" },
      ],
      points: [
        "deshalb · deswegen · darum · daher · trotzdem · dann · danach · außerdem · sonst · also.",
        "They are adverbs, not conjunctions — that is why they take a real slot.",
        "Trap: <em>nämlich</em> can NEVER stand at position 1. It lives in the middle field.",
      ],
      examples: [
        { de: "Es regnet, deshalb bleiben wir zu Hause.", en: "It's raining, that's why we're staying home." },
        { de: "Der Kurs war anstrengend, trotzdem hat er sich gelohnt.", en: "The course was tough, still it was worth it." },
        { de: "Ich muss mich beeilen, sonst verpasse ich den Bus.", en: "I have to hurry, otherwise I'll miss the bus." },
      ],
      contrast: {
        a: "Ich wohne hier, deshalb lerne ich Deutsch.",
        b: "Ich lerne Deutsch, weil ich hier wohne.",
        note: "deshalb takes slot 1 → inversion. weil takes no slot → verb to the end.",
      },
    },
    items: [
      { id: 1601, type: "conj", clauseA: "Ich wohne in Deutschland", clauseB: "Ich lerne Deutsch", answer: "deshalb",
        options: [
          { word:"deshalb", effect:"pos1", result:"Ich wohne in Deutschland, deshalb lerne ich Deutsch.", note:"Position 1 — lerne stays at 2, ich moves behind it." },
          { word:"weil", effect:"end", result:"Ich lerne Deutsch, weil ich in Deutschland wohne.", note:"Verb-final — same logic, opposite clause order." },
          { word:"denn", effect:"pos0", result:"Ich lerne Deutsch, denn ich wohne in Deutschland.", note:"Position 0 — nothing moves at all." },
          { word:"obwohl", effect:"end", result:"Ich lerne Deutsch, obwohl ich in Deutschland wohne.", note:"Verb-final, but \"although\" contradicts the logic." },
        ],
        why: "<em>deshalb</em> occupies position 1, so the verb must follow immediately." },
      { id: 1602, type: "order", en: "It's raining, that's why we're staying at home.",
        parts: [ {text:"Es regnet,",pos:"erg"}, {text:"deshalb",pos:"conj",label:"Position 1"}, {text:"bleiben",pos:"verb",label:"Pos 2"}, {text:"wir",pos:"subj"}, {text:"zu Hause.",pos:"local"} ],
        why: "Connector on 1 → verb on 2 → subject on 3." },
      { id: 1603, type: "fix", wrong: "Ich habe wenig Zeit, trotzdem ich gehe zum Sprachcafé.", correct: "Ich habe wenig Zeit, trotzdem gehe ich zum Sprachcafé.", badIndex: 6,
        why: "<em>trotzdem</em> fills position 1, so <em>gehe</em> comes next and <em>ich</em> after it." },
      { id: 1604, type: "order", en: "First I do my homework.",
        parts: [ {text:"Zuerst",pos:"conj",label:"Position 1"}, {text:"mache",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"die Hausaufgaben.",pos:"akk"} ],
        why: "Sequencing adverbs behave exactly like deshalb." },
      { id: 1605, type: "conj", clauseA: "Der Kurs war anstrengend", clauseB: "Er hat sich gelohnt", answer: "trotzdem",
        options: [
          { word:"trotzdem", effect:"pos1", result:"Der Kurs war anstrengend, trotzdem hat er sich gelohnt.", note:"Position 1 — hat at slot 2, er behind it." },
          { word:"obwohl", effect:"end", result:"Obwohl der Kurs anstrengend war, hat er sich gelohnt.", note:"Verb-final in the sub-clause — same meaning, different machinery." },
          { word:"deshalb", effect:"pos1", result:"Der Kurs war anstrengend, deshalb hat er sich gelohnt.", note:"Right slot, wrong logic — this says the effort CAUSED the payoff." },
          { word:"denn", effect:"pos0", result:"Der Kurs war anstrengend, denn er hat sich gelohnt.", note:"Position 0, and the causality is backwards." },
        ],
        why: "Concessive \"still / nevertheless\" as a position-1 adverb is <em>trotzdem</em>." },
      { id: 1606, type: "order", en: "I have to hurry, otherwise I'll miss the bus.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"muss",pos:"verb",label:"Pos 2"}, {text:"mich beeilen,",pos:"erg"}, {text:"sonst",pos:"conj",label:"Position 1"}, {text:"verpasse",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"den Bus.",pos:"akk"} ],
        why: "<em>sonst</em> is a slot-1 adverb — inversion follows." },
      { id: 1607, type: "fix", wrong: "Wir waren im Kino, danach wir sind essen gegangen.", correct: "Wir waren im Kino, danach sind wir essen gegangen.", badIndex: 6,
        why: "<em>danach</em> takes position 1, so <em>sind</em> must be element 2." },
      { id: 1608, type: "conj", clauseA: "Ich habe die Bewerbung geschrieben", clauseB: "Ich habe sie abgeschickt", answer: "dann",
        options: [
          { word:"dann", effect:"pos1", result:"Ich habe die Bewerbung geschrieben, dann habe ich sie abgeschickt.", note:"Position 1 — habe at 2, ich behind it." },
          { word:"und", effect:"pos0", result:"Ich habe die Bewerbung geschrieben und ich habe sie abgeschickt.", note:"Position 0 — correct German, but no sense of sequence." },
          { word:"bevor", effect:"end", result:"Bevor ich sie abgeschickt habe, habe ich die Bewerbung geschrieben.", note:"Verb-final, and the sequence is now stated backwards." },
          { word:"trotzdem", effect:"pos1", result:"Ich habe die Bewerbung geschrieben, trotzdem habe ich sie abgeschickt.", note:"Right slot, but \"nevertheless\" is illogical here." },
        ],
        why: "Sequence \"and then\" = <em>dann</em> at position 1, which forces inversion." },
      { id: 1609, type: "order", en: "The course is expensive, and besides it's far away.",
        parts: [ {text:"Der Kurs",pos:"subj"}, {text:"ist",pos:"verb",label:"Pos 2"}, {text:"teuer,",pos:"erg"}, {text:"außerdem",pos:"conj",label:"Position 1"}, {text:"liegt",pos:"verb",label:"Pos 2"}, {text:"er",pos:"subj"}, {text:"weit weg.",pos:"local"} ],
        why: "<em>außerdem</em> is an adverb in slot 1 — the verb follows." },
      { id: 1610, type: "fix", wrong: "Ich komme nicht mit. Nämlich ich habe keine Zeit.", correct: "Ich komme nicht mit. Ich habe nämlich keine Zeit.", badIndex: 4,
        why: "<em>nämlich</em> can never stand at position 1 — it belongs in the middle field, right after the verb." },
      { id: 1611, type: "conj", clauseA: "Ich habe kein Geld", clauseB: "Ich fahre nicht in Urlaub", answer: "deswegen",
        options: [
          { word:"deswegen", effect:"pos1", result:"Ich habe kein Geld, deswegen fahre ich nicht in Urlaub.", note:"Position 1 — fahre at 2, ich behind it." },
          { word:"weil", effect:"end", result:"Ich fahre nicht in Urlaub, weil ich kein Geld habe.", note:"Verb-final — habe lands at the very end." },
          { word:"aber", effect:"pos0", result:"Ich habe kein Geld, aber ich fahre nicht in Urlaub.", note:"Position 0, and the contrast makes no sense." },
          { word:"trotzdem", effect:"pos1", result:"Ich habe kein Geld, trotzdem fahre ich in Urlaub.", note:"Correct slot, opposite meaning." },
        ],
        why: "<em>deswegen</em> = deshalb: a position-1 adverb, so the verb is element 2." },
      { id: 1612, type: "order", en: "Today I'm free, so I'm going swimming.",
        parts: [ {text:"Heute",pos:"temp",label:"Pos 1"}, {text:"habe",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"frei,",pos:"erg"}, {text:"darum",pos:"conj",label:"Position 1"}, {text:"gehe",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"schwimmen.",pos:"erg"} ],
        why: "Two inversions in one sentence — first from <em>Heute</em>, then from <em>darum</em>." },
    ],
  },

  // --------------------------------------------------------- 7. Nebensatz
  {
    id: "nebensatz",
    label: "Nebensatz — Verb ans Ende",
    cefr: "B1",
    color: "#a78bfa",
    rule: {
      headline: "weil, dass, wenn, ob, obwohl … kick the conjugated verb to the very end of its clause.",
      diagram: [
        { text: "Ich lerne Deutsch,", label: "Hauptsatz", pos: "erg" },
        { text: "weil",               label: "Konjunktion", pos: "conj" },
        { text: "ich",                label: "Subjekt", pos: "subj" },
        { text: "in Deutschland",     label: "Mittelfeld", pos: "local" },
        { text: "wohne.",             label: "VERB — ENDE", pos: "verb" },
      ],
      points: [
        "weil · da · dass · ob · wenn · als · obwohl · damit · während · bevor · nachdem · seitdem · falls · sobald · bis.",
        "The main clause in front keeps its normal verb-second order.",
        "Order inside: Konjunktion → Subjekt → everything else → VERB.",
        "Separable verbs re-merge at the end: <em>ich mache auf</em> → <em>… weil ich aufmache</em>.",
        "With two verb parts the conjugated one comes LAST: <em>… dass er keine Zeit hat</em>.",
      ],
      examples: [
        { de: "Ich lerne Deutsch, weil ich in Deutschland wohne.", en: "I learn German because I live in Germany." },
        { de: "Ich denke, dass Deutsch sehr wichtig ist.", en: "I think that German is very important." },
        { de: "Ich rufe dich an, wenn ich fertig bin.", en: "I'll call you when I'm done." },
      ],
      contrast: {
        a: "…, weil ich in Deutschland wohne.",
        b: "…, denn ich wohne in Deutschland.",
        note: "Identical meaning. weil = verb to the end, denn = position 0.",
      },
    },
    items: [
      { id: 1701, type: "order", en: "I learn German because I live in Germany.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"lerne",pos:"verb",label:"Pos 2"}, {text:"Deutsch,",pos:"akk"}, {text:"weil",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"in Deutschland",pos:"local"}, {text:"wohne.",pos:"verb",label:"ENDE"} ],
        why: "<em>weil</em> is subordinating — <em>wohne</em> goes to the very end." },
      { id: 1702, type: "order", en: "I think that German is very important.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"denke,",pos:"verb",label:"Pos 2"}, {text:"dass",pos:"conj",label:"Konj."}, {text:"Deutsch",pos:"subj"}, {text:"sehr wichtig",pos:"erg"}, {text:"ist.",pos:"verb",label:"ENDE"} ],
        why: "<em>dass</em> sends <em>ist</em> to the end of its clause." },
      { id: 1703, type: "fix", wrong: "Ich glaube, dass er kommt morgen.", correct: "Ich glaube, dass er morgen kommt.", badIndex: 4,
        why: "In a dass-clause the verb is the last word — the time expression goes in front of it." },
      { id: 1704, type: "order", en: "I like doing sport when I have time.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"mache",pos:"verb",label:"Pos 2"}, {text:"gern Sport,",pos:"erg"}, {text:"wenn",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"Zeit",pos:"akk"}, {text:"habe.",pos:"verb",label:"ENDE"} ],
        why: "<em>wenn</em> is subordinating — <em>habe</em> closes the clause." },
      { id: 1705, type: "order", en: "I enjoy learning German although it is hard.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"lerne",pos:"verb",label:"Pos 2"}, {text:"gern Deutsch,",pos:"erg"}, {text:"obwohl",pos:"conj",label:"Konj."}, {text:"es",pos:"subj"}, {text:"schwer",pos:"erg"}, {text:"ist.",pos:"verb",label:"ENDE"} ],
        why: "<em>obwohl</em> pushes <em>ist</em> to the end — unlike <em>trotzdem</em>, which takes slot 1." },
      { id: 1706, type: "fix", wrong: "Ich weiß nicht, ob der Kurs beginnt am Montag.", correct: "Ich weiß nicht, ob der Kurs am Montag beginnt.", badIndex: 6,
        why: "<em>ob</em> is subordinating — <em>beginnt</em> must be the last word." },
      { id: 1707, type: "order", en: "I'll call you when I'm done.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"rufe",pos:"verb",label:"Pos 2"}, {text:"dich",pos:"akk"}, {text:"an,",pos:"verb",label:"Präfix"}, {text:"wenn",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"fertig",pos:"erg"}, {text:"bin.",pos:"verb",label:"ENDE"} ],
        why: "The main clause closes its own bracket with <em>an</em>; the sub-clause closes with <em>bin</em>." },
      { id: 1708, type: "order", en: "I'm opening the window because it's so warm.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"mache",pos:"verb",label:"Pos 2"}, {text:"das Fenster",pos:"akk"}, {text:"auf,",pos:"verb",label:"Präfix"}, {text:"weil",pos:"conj",label:"Konj."}, {text:"es",pos:"subj"}, {text:"so warm",pos:"erg"}, {text:"ist.",pos:"verb",label:"ENDE"} ],
        why: "Separable verb splits in the main clause but would re-merge inside a Nebensatz." },
      { id: 1709, type: "fix", wrong: "Er sagt, dass er hat keine Zeit.", correct: "Er sagt, dass er keine Zeit hat.", badIndex: 4,
        why: "With two verb parts in a Nebensatz the CONJUGATED one goes last." },
      { id: 1710, type: "conj", clauseA: "Ich lerne jeden Tag", clauseB: "Ich bestehe die Prüfung", answer: "damit",
        options: [
          { word:"damit", effect:"end", result:"Ich lerne jeden Tag, damit ich die Prüfung bestehe.", note:"Purpose — bestehe goes to the end." },
          { word:"weil", effect:"end", result:"Ich lerne jeden Tag, weil ich die Prüfung bestehe.", note:"Verb-final too, but \"because\" inverts the logic." },
          { word:"deshalb", effect:"pos1", result:"Ich bestehe die Prüfung, deshalb lerne ich jeden Tag.", note:"Position 1 — the verb stays at 2." },
          { word:"denn", effect:"pos0", result:"Ich lerne jeden Tag, denn ich bestehe die Prüfung.", note:"Position 0 — nothing moves, but the causality is backwards." },
        ],
        why: "Purpose (\"so that\") is <em>damit</em>, and it is verb-final." },
      { id: 1711, type: "order", en: "I'll wait until the bus comes.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"warte,",pos:"verb",label:"Pos 2"}, {text:"bis",pos:"conj",label:"Konj."}, {text:"der Bus",pos:"subj"}, {text:"kommt.",pos:"verb",label:"ENDE"} ],
        why: "<em>bis</em> as a conjunction is verb-final." },
      { id: 1712, type: "order", en: "Can you call me as soon as you have time?",
        parts: [ {text:"Kannst",pos:"verb",label:"Pos 1"}, {text:"du",pos:"subj"}, {text:"mich",pos:"akk"}, {text:"anrufen,",pos:"verb",label:"ENDE"}, {text:"sobald",pos:"conj",label:"Konj."}, {text:"du",pos:"subj"}, {text:"Zeit",pos:"akk"}, {text:"hast?",pos:"verb",label:"ENDE"} ],
        why: "A question can host a Nebensatz — each clause closes with its own verb." },
      { id: 1713, type: "conj", clauseA: "Ich gehe früh schlafen", clauseB: "Ich bin müde", answer: "weil",
        options: [
          { word:"weil", effect:"end", result:"Ich gehe früh schlafen, weil ich müde bin.", note:"Verb-final — bin lands last." },
          { word:"denn", effect:"pos0", result:"Ich gehe früh schlafen, denn ich bin müde.", note:"Same meaning, position 0 — nothing moves." },
          { word:"deshalb", effect:"pos1", result:"Ich bin müde, deshalb gehe ich früh schlafen.", note:"Position 1 — verb second, subject behind." },
          { word:"obwohl", effect:"end", result:"Ich gehe früh schlafen, obwohl ich müde bin.", note:"Verb-final, but \"although\" makes the sentence illogical." },
        ],
        why: "All three of weil / denn / deshalb express the same cause — only the word order differs." },
    ],
  },

  // ----------------------------------------------------- 8. Nebensatz vorn
  {
    id: "nebensatz_vorn",
    label: "Nebensatz zuerst — zwei Verben treffen sich",
    cefr: "B1",
    color: "#8b5cf6",
    rule: {
      headline: "A fronted subordinate clause fills position 1 all by itself — so the main verb comes right after the comma.",
      diagram: [
        { text: "Weil ich hier wohne,", label: "Pos 1 — ganzer Nebensatz", pos: "conj" },
        { text: "lerne",                label: "Pos 2 — VERB", pos: "verb" },
        { text: "ich",                  label: "Subjekt", pos: "subj" },
        { text: "Deutsch.",             label: "Rest", pos: "erg" },
      ],
      points: [
        "The whole clause counts as ONE element, so the verb-second rule is untouched.",
        "The give-away pattern is <em>… VERB, VERB …</em> — two verbs meeting across the comma.",
        "The subject of the main clause always lands behind that verb.",
      ],
      examples: [
        { de: "Weil ich in Deutschland wohne, lerne ich Deutsch.", en: "Because I live in Germany, I learn German." },
        { de: "Obwohl der Kurs schwer ist, macht er mir Spaß.", en: "Although the course is hard, I enjoy it." },
        { de: "Wenn ich Zeit habe, gehe ich ins Sprachcafé.", en: "When I have time I go to the language café." },
      ],
      contrast: {
        a: "Ich lerne Deutsch, weil ich hier wohne.",
        b: "Weil ich hier wohne, lerne ich Deutsch.",
        note: "Same two clauses. Fronting the Nebensatz forces inversion in the main clause.",
      },
    },
    items: [
      { id: 1801, type: "order", en: "Because I live in Germany, I learn German.",
        parts: [ {text:"Weil",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"in Deutschland",pos:"local"}, {text:"wohne,",pos:"verb",label:"ENDE"}, {text:"lerne",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"Deutsch.",pos:"akk"} ],
        why: "The Nebensatz is position 1, so <em>lerne</em> follows immediately after the comma." },
      { id: 1802, type: "fix", wrong: "Obwohl der Kurs schwer ist, er macht mir Spaß.", correct: "Obwohl der Kurs schwer ist, macht er mir Spaß.", badIndex: 6,
        why: "Position 1 is already used up by the sub-clause — <em>macht</em> must be element 2." },
      { id: 1803, type: "order", en: "When I have time I go to the language café.",
        parts: [ {text:"Wenn",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"Zeit",pos:"akk"}, {text:"habe,",pos:"verb",label:"ENDE"}, {text:"gehe",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"ins Sprachcafé.",pos:"local"} ],
        why: "<em>habe, gehe</em> — the two verbs meet across the comma." },
      { id: 1804, type: "order", en: "So that I pass the exam, I study every day.",
        parts: [ {text:"Damit",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"die Prüfung",pos:"akk"}, {text:"bestehe,",pos:"verb",label:"ENDE"}, {text:"lerne",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"jeden Tag.",pos:"temp"} ],
        why: "Fronted purpose clause → inversion in the main clause." },
      { id: 1805, type: "fix", wrong: "Nachdem ich gegessen habe, ich gehe spazieren.", correct: "Nachdem ich gegessen habe, gehe ich spazieren.", badIndex: 5,
        why: "The sub-clause is position 1 — the main verb comes straight after the comma." },
      { id: 1806, type: "order", en: "Since I study German daily, I feel more confident.",
        parts: [ {text:"Seitdem",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"täglich Deutsch",pos:"akk"}, {text:"lerne,",pos:"verb",label:"ENDE"}, {text:"fühle",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"mich sicherer.",pos:"erg"} ],
        why: "<em>lerne, fühle</em> — verb, comma, verb." },
      { id: 1807, type: "order", en: "Before I came to Germany I spoke no German.",
        parts: [ {text:"Bevor",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"nach Deutschland",pos:"local"}, {text:"gekommen bin,",pos:"verb",label:"ENDE"}, {text:"habe",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"kein Wort Deutsch gesprochen.",pos:"erg"} ],
        why: "Inside the sub-clause the conjugated <em>bin</em> is last; in the main clause <em>habe</em> is second." },
      { id: 1808, type: "fix", wrong: "Als ich klein war, ich wollte Pilot werden.", correct: "Als ich klein war, wollte ich Pilot werden.", badIndex: 5,
        why: "<em>wollte</em> must be element 2 — the sub-clause already took position 1." },
      { id: 1809, type: "order", en: "While he cycles, he listens to German podcasts.",
        parts: [ {text:"Während",pos:"conj",label:"Konj."}, {text:"er",pos:"subj"}, {text:"Fahrrad",pos:"akk"}, {text:"fährt,",pos:"verb",label:"ENDE"}, {text:"hört",pos:"verb",label:"Pos 2"}, {text:"er",pos:"subj"}, {text:"deutsche Podcasts.",pos:"akk"} ],
        why: "Fronted temporal clause → verb, then subject." },
      { id: 1810, type: "order", en: "Since I want to stay in Germany, German is very important to me.",
        parts: [ {text:"Da",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"in Deutschland",pos:"local"}, {text:"bleiben möchte,",pos:"verb",label:"ENDE"}, {text:"ist",pos:"verb",label:"Pos 2"}, {text:"Deutsch",pos:"subj"}, {text:"sehr wichtig für mich.",pos:"erg"} ],
        why: "<em>da</em> is the formal \"since\" — always fronted, always verb-final." },
      { id: 1811, type: "fix", wrong: "Wenn es regnet, wir bleiben zu Hause.", correct: "Wenn es regnet, bleiben wir zu Hause.", badIndex: 4,
        why: "Sub-clause = position 1, so <em>bleiben</em> is element 2 and <em>wir</em> follows." },
      { id: 1812, type: "order", en: "If you have questions, just write to me.",
        parts: [ {text:"Falls",pos:"conj",label:"Konj."}, {text:"du",pos:"subj"}, {text:"Fragen",pos:"akk"}, {text:"hast,",pos:"verb",label:"ENDE"}, {text:"schreib",pos:"verb",label:"Pos 2"}, {text:"mir",pos:"dativ"}, {text:"einfach.",pos:"erg"} ],
        why: "Even an imperative main clause follows the fronted sub-clause directly." },
    ],
  },

  // ------------------------------------------------------------ 9. TeKaMoLo
  {
    id: "tekamolo",
    label: "TeKaMoLo — das Mittelfeld ordnen",
    cefr: "B2",
    color: "#34d399",
    rule: {
      headline: "Inside the middle field the default order is Temporal → Kausal → Modal → Lokal.",
      diagram: [
        { text: "Ich",             label: "Subjekt", pos: "subj" },
        { text: "fahre",           label: "Pos 2", pos: "verb" },
        { text: "morgen früh",     label: "Te — wann?", pos: "temp" },
        { text: "wegen der Prüfung", label: "Ka — warum?", pos: "erg" },
        { text: "mit dem Zug",     label: "Mo — wie?", pos: "manner" },
        { text: "nach Hamburg.",   label: "Lo — wohin?", pos: "local" },
      ],
      points: [
        "TeKaMoLo is a default, not a law — fronting one element to position 1 always stays possible.",
        "Pronouns jump to the FRONT of the middle field, before every noun and every adverbial.",
        "With two pronouns: accusative before dative (<em>Ich gebe es ihr</em>).",
        "<em>nicht</em> goes late — right before the element it negates, and before the closing verb part.",
      ],
      examples: [
        { de: "Ich gehe jeden Abend zu Fuß nach Hause.", en: "I walk home on foot every evening." },
        { de: "Ich habe es meiner Schwester gestern gegeben.", en: "I gave it to my sister yesterday." },
        { de: "Ich kann dir heute leider nicht helfen.", en: "Unfortunately I can't help you today." },
      ],
      contrast: {
        a: "Ich gebe meiner Schwester das Buch.",
        b: "Ich gebe es meiner Schwester.",
        note: "Turn the object into a pronoun and it overtakes everything else.",
      },
    },
    items: [
      { id: 1901, type: "order", en: "Tomorrow morning I'm taking the train to Hamburg.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"fahre",pos:"verb",label:"Pos 2"}, {text:"morgen früh",pos:"temp",label:"Te"}, {text:"mit dem Zug",pos:"manner",label:"Mo"}, {text:"nach Hamburg.",pos:"local",label:"Lo"} ],
        why: "Time before manner before place — Te, Mo, Lo." },
      { id: 1902, type: "order", en: "I walk home on foot every evening.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"gehe",pos:"verb",label:"Pos 2"}, {text:"jeden Abend",pos:"temp",label:"Te"}, {text:"zu Fuß",pos:"manner",label:"Mo"}, {text:"nach Hause.",pos:"local",label:"Lo"} ],
        why: "Classic Te–Mo–Lo chain." },
      { id: 1903, type: "order", en: "She writes her application on her laptop tomorrow morning.",
        parts: [ {text:"Sie",pos:"subj"}, {text:"schreibt",pos:"verb",label:"Pos 2"}, {text:"morgen früh",pos:"temp",label:"Te"}, {text:"mit dem Laptop",pos:"manner",label:"Mo"}, {text:"ihre Bewerbung.",pos:"akk"} ],
        why: "The accusative object closes the middle field after the adverbials." },
      { id: 1904, type: "fix", wrong: "Ich fahre mit dem Zug morgen nach Hamburg.", correct: "Ich fahre morgen mit dem Zug nach Hamburg.", badIndex: 5,
        why: "Temporal comes before modal — <em>morgen</em> belongs in front of <em>mit dem Zug</em>." },
      { id: 1905, type: "order", en: "We play basketball together on the sports field every Sunday.",
        parts: [ {text:"Wir",pos:"subj"}, {text:"spielen",pos:"verb",label:"Pos 2"}, {text:"jeden Sonntag",pos:"temp",label:"Te"}, {text:"zusammen",pos:"manner",label:"Mo"}, {text:"Basketball",pos:"akk"}, {text:"auf dem Sportplatz.",pos:"local",label:"Lo"} ],
        why: "Te, Mo, object, Lo — the place rounds the sentence off." },
      { id: 1906, type: "order", en: "I gave it to my sister yesterday.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"habe",pos:"verb",label:"Pos 2"}, {text:"es",pos:"akk",label:"Pronomen"}, {text:"meiner Schwester",pos:"dativ"}, {text:"gestern",pos:"temp",label:"Te"}, {text:"gegeben.",pos:"verb",label:"ENDE"} ],
        why: "The pronoun <em>es</em> jumps to the front of the middle field, ahead of the noun and the time." },
      { id: 1907, type: "fix", wrong: "Ich habe gestern es meiner Schwester gegeben.", correct: "Ich habe es gestern meiner Schwester gegeben.", badIndex: 3,
        why: "Pronouns come first in the middle field — before any time expression." },
      { id: 1908, type: "order", en: "Unfortunately I can't help you today.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"kann",pos:"verb",label:"Pos 2"}, {text:"dir",pos:"dativ",label:"Pronomen"}, {text:"heute",pos:"temp",label:"Te"}, {text:"leider",pos:"manner",label:"Mo"}, {text:"nicht",pos:"erg"}, {text:"helfen.",pos:"verb",label:"ENDE"} ],
        why: "Pronoun first, then Te, then Mo, then <em>nicht</em> just before the closing verb." },
      { id: 1909, type: "order", en: "He moved to Bremen last year because of work.",
        parts: [ {text:"Er",pos:"subj"}, {text:"ist",pos:"verb",label:"Pos 2"}, {text:"letztes Jahr",pos:"temp",label:"Te"}, {text:"wegen der Arbeit",pos:"erg",label:"Ka"}, {text:"nach Bremen",pos:"local",label:"Lo"}, {text:"gezogen.",pos:"verb",label:"ENDE"} ],
        why: "A full Te–Ka–Lo chain inside the Perfekt bracket." },
      { id: 1910, type: "fix", wrong: "Ich gehe zu Fuß immer nach Hause.", correct: "Ich gehe immer zu Fuß nach Hause.", badIndex: 4,
        why: "<em>immer</em> is temporal, so it goes before the modal <em>zu Fuß</em>." },
      { id: 1911, type: "order", en: "I'll bring you the book tomorrow.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"bringe",pos:"verb",label:"Pos 2"}, {text:"dir",pos:"dativ",label:"Pronomen"}, {text:"morgen",pos:"temp",label:"Te"}, {text:"das Buch",pos:"akk"}, {text:"mit.",pos:"verb",label:"Präfix"} ],
        why: "Pronoun, time, noun object, then the separable prefix." },
      { id: 1912, type: "order", en: "The train is arriving late today because of the strike.",
        parts: [ {text:"Der Zug",pos:"subj"}, {text:"kommt",pos:"verb",label:"Pos 2"}, {text:"heute",pos:"temp",label:"Te"}, {text:"wegen des Streiks",pos:"erg",label:"Ka"}, {text:"später",pos:"manner",label:"Mo"}, {text:"an.",pos:"verb",label:"Präfix"} ],
        why: "Te–Ka–Mo, and the prefix still closes the bracket." },
      { id: 1913, type: "fix", wrong: "Ich habe nicht ihn gestern gesehen.", correct: "Ich habe ihn gestern nicht gesehen.", badIndex: 2,
        why: "The pronoun goes to the front; <em>nicht</em> goes late, just before the Partizip II." },
    ],
  },

  // -------------------------------------------------------- 10. Relativsatz
  {
    id: "relativsatz",
    label: "Relativsätze — Verb ans Ende, Kasus aus der Rolle",
    cefr: "B2",
    color: "#f472b6",
    rule: {
      headline: "The relative pronoun takes gender and number from the noun, but its CASE from its job inside the relative clause.",
      diagram: [
        { text: "Das ist der Kurs,", label: "Bezugswort", pos: "erg" },
        { text: "der",              label: "Relativpron. — Nom.", pos: "conj" },
        { text: "mir",              label: "Dativ", pos: "dativ" },
        { text: "am besten",        label: "Mittelfeld", pos: "manner" },
        { text: "gefällt.",         label: "VERB — ENDE", pos: "verb" },
      ],
      points: [
        "A relative clause is a Nebensatz — the conjugated verb is always last.",
        "With a preposition the preposition comes FIRST: <em>der Lehrer, mit dem ich spreche</em>.",
        "Genitive: <em>dessen</em> (m/n), <em>deren</em> (f/pl) — \"whose\".",
        "Use <em>was</em> after alles, nichts, etwas, vieles and after a whole clause; <em>wo</em> for places.",
      ],
      examples: [
        { de: "Der Lehrer, mit dem ich gesprochen habe, war sehr nett.", en: "The teacher I spoke with was very nice." },
        { de: "Ich kenne einen Studenten, dessen Bruder in Berlin arbeitet.", en: "I know a student whose brother works in Berlin." },
        { de: "Das ist alles, was ich darüber weiß.", en: "That's all I know about it." },
      ],
      contrast: {
        a: "der Freund, der mir hilft",
        b: "der Freund, dem ich helfe",
        note: "Same noun. Nominative when he does the helping, dative when he receives it.",
      },
    },
    items: [
      { id: 2001, type: "order", en: "That's the course I like best.",
        parts: [ {text:"Das ist",pos:"erg"}, {text:"der Kurs,",pos:"subj"}, {text:"der",pos:"conj",label:"Relativpron."}, {text:"mir",pos:"dativ"}, {text:"am besten",pos:"manner"}, {text:"gefällt.",pos:"verb",label:"ENDE"} ],
        why: "The pronoun is the subject of the relative clause → nominative <em>der</em>, verb last." },
      { id: 2002, type: "order", en: "The teacher I spoke with was very nice.",
        parts: [ {text:"Der Lehrer,",pos:"subj"}, {text:"mit dem",pos:"conj",label:"Präp. + Rel."}, {text:"ich",pos:"subj"}, {text:"gesprochen",pos:"verb"}, {text:"habe,",pos:"verb",label:"ENDE"}, {text:"war",pos:"verb",label:"Pos 2"}, {text:"sehr nett.",pos:"erg"} ],
        why: "<em>sprechen mit</em> takes dative, so the preposition leads and <em>dem</em> follows it." },
      { id: 2003, type: "fix", wrong: "Das Buch, das ich habe gekauft, ist teuer.", correct: "Das Buch, das ich gekauft habe, ist teuer.", badIndex: 4,
        why: "In a relative clause the conjugated <em>habe</em> comes last, after the Partizip II." },
      { id: 2004, type: "order", en: "The city I live in is called Bremen.",
        parts: [ {text:"Die Stadt,",pos:"subj"}, {text:"in der",pos:"conj",label:"Präp. + Rel."}, {text:"ich",pos:"subj"}, {text:"wohne,",pos:"verb",label:"ENDE"}, {text:"heißt",pos:"verb",label:"Pos 2"}, {text:"Bremen.",pos:"erg"} ],
        why: "German never strands the preposition — it leads the relative clause." },
      { id: 2005, type: "order", en: "I know a student whose brother works in Berlin.",
        parts: [ {text:"Ich kenne",pos:"erg"}, {text:"einen Studenten,",pos:"akk"}, {text:"dessen",pos:"conj",label:"Genitiv"}, {text:"Bruder",pos:"subj"}, {text:"in Berlin",pos:"local"}, {text:"arbeitet.",pos:"verb",label:"ENDE"} ],
        why: "<em>dessen</em> = \"whose\" for a masculine antecedent; the verb still closes the clause." },
      { id: 2006, type: "order", en: "That's all I know about it.",
        parts: [ {text:"Das ist alles,",pos:"erg"}, {text:"was",pos:"conj",label:"Relativpron."}, {text:"ich",pos:"subj"}, {text:"darüber",pos:"erg"}, {text:"weiß.",pos:"verb",label:"ENDE"} ],
        why: "After <em>alles</em> the relative pronoun is <em>was</em>, never <em>das</em>." },
      { id: 2007, type: "fix", wrong: "Ich suche eine Wohnung, die nicht ist zu teuer.", correct: "Ich suche eine Wohnung, die nicht zu teuer ist.", badIndex: 6,
        why: "Relative clause = Nebensatz → <em>ist</em> is the final word." },
      { id: 2008, type: "order", en: "The film we talked about yesterday is still showing.",
        parts: [ {text:"Der Film,",pos:"subj"}, {text:"über den",pos:"conj",label:"Präp. + Rel."}, {text:"wir",pos:"subj"}, {text:"gestern",pos:"temp"}, {text:"gesprochen haben,",pos:"verb",label:"ENDE"}, {text:"läuft",pos:"verb",label:"Pos 2"}, {text:"noch im Kino.",pos:"local"} ],
        why: "<em>sprechen über</em> takes accusative → <em>über den</em>." },
      { id: 2009, type: "order", en: "That's the colleague whose husband is also learning German.",
        parts: [ {text:"Das ist",pos:"erg"}, {text:"die Kollegin,",pos:"subj"}, {text:"deren",pos:"conj",label:"Genitiv"}, {text:"Mann",pos:"subj"}, {text:"auch Deutsch",pos:"akk"}, {text:"lernt.",pos:"verb",label:"ENDE"} ],
        why: "<em>deren</em> is the feminine and plural \"whose\"." },
      { id: 2010, type: "fix", wrong: "Das ist der Grund, warum ich habe Deutsch gelernt.", correct: "Das ist der Grund, warum ich Deutsch gelernt habe.", badIndex: 6,
        why: "<em>warum</em> introduces a Nebensatz — the conjugated <em>habe</em> goes last." },
      { id: 2011, type: "order", en: "The people I work with come from many countries.",
        parts: [ {text:"Die Leute,",pos:"subj"}, {text:"mit denen",pos:"conj",label:"Präp. + Rel."}, {text:"ich",pos:"subj"}, {text:"arbeite,",pos:"verb",label:"ENDE"}, {text:"kommen",pos:"verb",label:"Pos 2"}, {text:"aus vielen Ländern.",pos:"local"} ],
        why: "Plural dative after <em>mit</em> → <em>denen</em>." },
      { id: 2012, type: "order", en: "Bremen is a city where you can live well.",
        parts: [ {text:"Bremen ist",pos:"erg"}, {text:"eine Stadt,",pos:"subj"}, {text:"in der",pos:"conj",label:"Präp. + Rel."}, {text:"man",pos:"subj"}, {text:"gut",pos:"manner"}, {text:"leben",pos:"verb"}, {text:"kann.",pos:"verb",label:"ENDE"} ],
        why: "Two verb parts in a Nebensatz: the modal <em>kann</em> is the very last word." },
    ],
  },

  // ------------------------------------------------------ 11. zu + Infinitiv
  {
    id: "zu_infinitiv",
    label: "zu + Infinitiv — um … zu, ohne … zu",
    cefr: "B2",
    color: "#38bdf8",
    rule: {
      headline: "The zu-Infinitiv closes its clause, and with separable verbs the <em>zu</em> slides inside the word.",
      diagram: [
        { text: "Ich",        label: "Subjekt", pos: "subj" },
        { text: "versuche,",  label: "Pos 2", pos: "verb" },
        { text: "jeden Tag",  label: "Mittelfeld", pos: "temp" },
        { text: "Deutsch",    label: "Mittelfeld", pos: "akk" },
        { text: "zu lernen.", label: "zu + Infinitiv — ENDE", pos: "verb" },
      ],
      points: [
        "<em>um … zu</em> = purpose, and only when both clauses share the same subject — otherwise use <em>damit</em>.",
        "<em>ohne … zu</em> = \"without doing\"; <em>anstatt … zu</em> = \"instead of doing\".",
        "Separable verbs infix it: anrufen → <em>anzurufen</em>, aufstehen → <em>aufzustehen</em>.",
        "Modal verbs never take <em>zu</em>: <em>Ich muss lernen</em>, not \"zu lernen\".",
      ],
      examples: [
        { de: "Ich lerne jeden Tag, um die Prüfung zu bestehen.", en: "I study every day in order to pass the exam." },
        { de: "Ich habe vergessen, dich anzurufen.", en: "I forgot to call you." },
        { de: "Er ging nach Hause, ohne sich zu verabschieden.", en: "He went home without saying goodbye." },
      ],
      contrast: {
        a: "Ich lerne, um die Prüfung zu bestehen.",
        b: "Ich lerne, damit meine Familie stolz ist.",
        note: "Same subject → um…zu. Different subject → damit.",
      },
    },
    items: [
      { id: 2101, type: "order", en: "I try to learn German every day.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"versuche,",pos:"verb",label:"Pos 2"}, {text:"jeden Tag",pos:"temp"}, {text:"Deutsch",pos:"akk"}, {text:"zu lernen.",pos:"verb",label:"ENDE"} ],
        why: "The zu-Infinitiv is the last element of its clause." },
      { id: 2102, type: "order", en: "I study every day in order to pass the exam.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"lerne",pos:"verb",label:"Pos 2"}, {text:"jeden Tag,",pos:"temp"}, {text:"um",pos:"conj",label:"um … zu"}, {text:"die Prüfung",pos:"akk"}, {text:"zu bestehen.",pos:"verb",label:"ENDE"} ],
        why: "<em>um</em> opens the clause, <em>zu bestehen</em> closes it." },
      { id: 2103, type: "order", en: "I forgot to call you.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"habe",pos:"verb",label:"Pos 2"}, {text:"vergessen,",pos:"verb",label:"ENDE"}, {text:"dich",pos:"akk"}, {text:"anzurufen.",pos:"verb",label:"zu-Infinitiv"} ],
        why: "<em>anrufen</em> is separable, so the <em>zu</em> goes inside: <em>anzurufen</em>." },
      { id: 2104, type: "order", en: "He went home without saying goodbye.",
        parts: [ {text:"Er",pos:"subj"}, {text:"ging",pos:"verb",label:"Pos 2"}, {text:"nach Hause,",pos:"local"}, {text:"ohne",pos:"conj",label:"ohne … zu"}, {text:"sich",pos:"akk"}, {text:"zu verabschieden.",pos:"verb",label:"ENDE"} ],
        why: "<em>ohne … zu</em> works exactly like <em>um … zu</em>." },
      { id: 2105, type: "fix", wrong: "Ich freue mich darauf, dich zu sehen bald.", correct: "Ich freue mich darauf, dich bald zu sehen.", badIndex: 7,
        why: "Nothing may follow the zu-Infinitiv — the time expression goes in front of it." },
      { id: 2106, type: "order", en: "It's important to practise a little every day.",
        parts: [ {text:"Es",pos:"subj"}, {text:"ist",pos:"verb",label:"Pos 2"}, {text:"wichtig,",pos:"erg"}, {text:"jeden Tag",pos:"temp"}, {text:"ein bisschen",pos:"manner"}, {text:"zu üben.",pos:"verb",label:"ENDE"} ],
        why: "The zu-clause always ends the sentence." },
      { id: 2107, type: "order", en: "Instead of studying he played all day.",
        parts: [ {text:"Anstatt",pos:"conj",label:"anstatt … zu"}, {text:"zu lernen,",pos:"verb",label:"ENDE"}, {text:"hat",pos:"verb",label:"Pos 2"}, {text:"er",pos:"subj"}, {text:"den ganzen Tag",pos:"temp"}, {text:"gespielt.",pos:"verb",label:"ENDE"} ],
        why: "A fronted zu-clause is position 1, so <em>hat</em> is element 2." },
      { id: 2108, type: "fix", wrong: "Ich habe keine Zeit, zu kommen heute.", correct: "Ich habe keine Zeit, heute zu kommen.", badIndex: 6,
        why: "<em>heute</em> belongs inside the clause, before <em>zu kommen</em>." },
      { id: 2109, type: "order", en: "I'm going to Berlin to visit my friends.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"fahre",pos:"verb",label:"Pos 2"}, {text:"nach Berlin,",pos:"local"}, {text:"um",pos:"conj",label:"um … zu"}, {text:"meine Freunde",pos:"akk"}, {text:"zu besuchen.",pos:"verb",label:"ENDE"} ],
        why: "Same subject in both clauses, so <em>um … zu</em> is correct." },
      { id: 2110, type: "order", en: "She has started doing sport regularly.",
        parts: [ {text:"Sie",pos:"subj"}, {text:"hat",pos:"verb",label:"Pos 2"}, {text:"angefangen,",pos:"verb",label:"ENDE"}, {text:"regelmäßig",pos:"manner"}, {text:"Sport",pos:"akk"}, {text:"zu machen.",pos:"verb",label:"ENDE"} ],
        why: "Main clause bracket closes with <em>angefangen</em>; the zu-clause closes the sentence." },
      { id: 2111, type: "fix", wrong: "Ich versuche, zu verstehen alles.", correct: "Ich versuche, alles zu verstehen.", badIndex: 4,
        why: "The object goes in front of the zu-Infinitiv, never after it." },
      { id: 2112, type: "order", en: "I'm asking you to help me with the application.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"bitte",pos:"verb",label:"Pos 2"}, {text:"dich,",pos:"akk"}, {text:"mir",pos:"dativ"}, {text:"bei der Bewerbung",pos:"erg"}, {text:"zu helfen.",pos:"verb",label:"ENDE"} ],
        why: "Pronoun first inside the zu-clause, verb last." },
    ],
  },

  // -------------------------------------------------------------- 12. Passiv
  {
    id: "passiv",
    label: "Passiv — werden ans Ende, im Nebensatz ganz zuletzt",
    cefr: "B2",
    color: "#fbbf24",
    rule: {
      headline: "Vorgangspassiv = werden + Partizip II. The Partizip closes the bracket — unless a modal or a Nebensatz stacks more verbs behind it.",
      diagram: [
        { text: "Die Bewerbung",  label: "Subjekt", pos: "subj" },
        { text: "wird",           label: "Pos 2 — werden", pos: "verb" },
        { text: "morgen",         label: "Te", pos: "temp" },
        { text: "von mir",        label: "Agens", pos: "erg" },
        { text: "abgeschickt.",   label: "Partizip II — ENDE", pos: "verb" },
      ],
      points: [
        "Vorgangspassiv (<em>wird geschlossen</em>) = the action. Zustandspassiv (<em>ist geschlossen</em>) = the result.",
        "Agent: <em>von</em> + Dativ for people, <em>durch</em> + Akkusativ for means.",
        "With a modal the order is Partizip II → <em>werden</em> → modal: <em>… ausgefüllt werden muss</em>.",
        "In a Nebensatz the whole verb block moves to the end and the conjugated form comes LAST.",
        "Perfekt Passiv uses <em>worden</em>, not <em>geworden</em>.",
      ],
      examples: [
        { de: "Das Formular muss bis Freitag ausgefüllt werden.", en: "The form has to be filled in by Friday." },
        { de: "Ich weiß, dass die Prüfung im Juli geschrieben wird.", en: "I know the exam is written in July." },
        { de: "Es ist mir gesagt worden, dass der Kurs ausfällt.", en: "I was told the course is cancelled." },
      ],
      contrast: {
        a: "Die Tür wird geschlossen.",
        b: "Die Tür ist geschlossen.",
        note: "werden = it is being closed (process). sein = it is closed (state).",
      },
    },
    items: [
      { id: 2201, type: "order", en: "The application will be sent by me tomorrow.",
        parts: [ {text:"Die Bewerbung",pos:"subj"}, {text:"wird",pos:"verb",label:"Pos 2"}, {text:"morgen",pos:"temp",label:"Te"}, {text:"von mir",pos:"erg",label:"Agens"}, {text:"abgeschickt.",pos:"verb",label:"ENDE"} ],
        why: "<em>wird</em> at slot 2, Partizip II closing the bracket." },
      { id: 2202, type: "order", en: "The form has to be filled in by Friday.",
        parts: [ {text:"Das Formular",pos:"subj"}, {text:"muss",pos:"verb",label:"Pos 2"}, {text:"bis Freitag",pos:"temp",label:"Te"}, {text:"ausgefüllt",pos:"verb"}, {text:"werden.",pos:"verb",label:"ENDE"} ],
        why: "Modal + Passiv: Partizip II first, then the infinitive <em>werden</em>." },
      { id: 2203, type: "fix", wrong: "Ich weiß, dass die Prüfung wird im Juli geschrieben.", correct: "Ich weiß, dass die Prüfung im Juli geschrieben wird.", badIndex: 5,
        why: "In a dass-clause the conjugated <em>wird</em> is the last word of all." },
      { id: 2204, type: "order", en: "In Germany the shops are closed on Sundays.",
        parts: [ {text:"In Deutschland",pos:"local",label:"Pos 1"}, {text:"werden",pos:"verb",label:"Pos 2"}, {text:"sonntags",pos:"temp",label:"Te"}, {text:"die Geschäfte",pos:"subj"}, {text:"geschlossen.",pos:"verb",label:"ENDE"} ],
        why: "Fronting the place triggers inversion; the Partizip still closes the bracket." },
      { id: 2205, type: "order", en: "I hope that I'm helped.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"hoffe,",pos:"verb",label:"Pos 2"}, {text:"dass",pos:"conj",label:"Konj."}, {text:"mir",pos:"dativ"}, {text:"geholfen",pos:"verb"}, {text:"wird.",pos:"verb",label:"ENDE"} ],
        why: "<em>helfen</em> takes dative, so the passive has no nominative subject at all." },
      { id: 2206, type: "fix", wrong: "Das Problem konnte nicht werden gelöst.", correct: "Das Problem konnte nicht gelöst werden.", badIndex: 4,
        why: "Partizip II comes before <em>werden</em> — the infinitive closes the bracket." },
      { id: 2207, type: "order", en: "The course is taught by a native speaker.",
        parts: [ {text:"Der Kurs",pos:"subj"}, {text:"wird",pos:"verb",label:"Pos 2"}, {text:"von einer Muttersprachlerin",pos:"erg",label:"Agens"}, {text:"unterrichtet.",pos:"verb",label:"ENDE"} ],
        why: "The agent uses <em>von</em> + Dativ." },
      { id: 2208, type: "order", en: "I was told that the course is cancelled.",
        parts: [ {text:"Es",pos:"subj"}, {text:"ist",pos:"verb",label:"Pos 2"}, {text:"mir",pos:"dativ"}, {text:"gesagt",pos:"verb"}, {text:"worden,",pos:"verb",label:"ENDE"}, {text:"dass",pos:"conj",label:"Konj."}, {text:"der Kurs",pos:"subj"}, {text:"ausfällt.",pos:"verb",label:"ENDE"} ],
        why: "Perfekt Passiv uses <em>worden</em>; the dass-clause closes with its own verb." },
      { id: 2209, type: "fix", wrong: "Die Tür ist geschlossen worden gestern.", correct: "Die Tür ist gestern geschlossen worden.", badIndex: 5,
        why: "Nothing follows the closing verb block — <em>gestern</em> goes inside the bracket." },
      { id: 2210, type: "order", en: "The certificate can be applied for online.",
        parts: [ {text:"Das Zertifikat",pos:"subj"}, {text:"kann",pos:"verb",label:"Pos 2"}, {text:"online",pos:"manner",label:"Mo"}, {text:"beantragt",pos:"verb"}, {text:"werden.",pos:"verb",label:"ENDE"} ],
        why: "Modal at slot 2, then Partizip II, then <em>werden</em>." },
      { id: 2211, type: "order", en: "After the application had been sent, I waited for a reply.",
        parts: [ {text:"Nachdem",pos:"conj",label:"Konj."}, {text:"die Bewerbung",pos:"subj"}, {text:"abgeschickt",pos:"verb"}, {text:"worden war,",pos:"verb",label:"ENDE"}, {text:"wartete",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"auf Antwort.",pos:"erg"} ],
        why: "Plusquamperfekt Passiv inside a fronted Nebensatz — <em>war</em> is the final word there." },
      { id: 2212, type: "fix", wrong: "Er sagt, dass das Zimmer muss aufgeräumt werden.", correct: "Er sagt, dass das Zimmer aufgeräumt werden muss.", badIndex: 5,
        why: "Modal + Passiv in a Nebensatz: Partizip → werden → the conjugated modal, dead last." },
    ],
  },

  // --------------------------------------------------------- 13. Konjunktiv II
  {
    id: "konjunktiv2",
    label: "Konjunktiv II — irreale Bedingungen",
    cefr: "B2",
    color: "#c084fc",
    rule: {
      headline: "wenn-clause verb-final, main clause verb-second. Drop the <em>wenn</em> and the verb starts the clause instead.",
      diagram: [
        { text: "Wenn ich Zeit hätte,", label: "Pos 1 — Nebensatz", pos: "conj" },
        { text: "würde",                label: "Pos 2 — VERB", pos: "verb" },
        { text: "ich",                  label: "Subjekt", pos: "subj" },
        { text: "mehr lesen.",          label: "Rest", pos: "erg" },
      ],
      points: [
        "<em>würde</em> + Infinitiv is the everyday form; hätte, wäre, könnte, müsste, sollte, wüsste use their own.",
        "Never use <em>würde</em> together with <em>hätte</em>/<em>wäre</em> in the same clause.",
        "You may drop <em>wenn</em> — then the clause opens with the verb: <em>Hätte ich Zeit, …</em>.",
        "Past: hätte / wäre + Partizip II — <em>Wenn ich das gewusst hätte, wäre ich nicht gekommen.</em>",
        "Polite requests are Konjunktiv II too: <em>Könntest du mir bitte helfen?</em>",
      ],
      examples: [
        { de: "Wenn ich mehr Zeit hätte, würde ich mehr lesen.", en: "If I had more time I'd read more." },
        { de: "Hätte ich mehr Geld, würde ich eine Weltreise machen.", en: "Had I more money, I'd travel the world." },
        { de: "Ohne deine Hilfe hätte ich die Prüfung nicht bestanden.", en: "Without your help I wouldn't have passed." },
      ],
      contrast: {
        a: "Wenn ich Zeit hätte, würde ich kommen.",
        b: "Hätte ich Zeit, würde ich kommen.",
        note: "Drop wenn → the verb jumps to the front of the clause. The main clause is unchanged.",
      },
    },
    items: [
      { id: 2301, type: "order", en: "If I had more time I'd read more.",
        parts: [ {text:"Wenn",pos:"conj",label:"Konj."}, {text:"ich",pos:"subj"}, {text:"mehr Zeit",pos:"akk"}, {text:"hätte,",pos:"verb",label:"ENDE"}, {text:"würde",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"mehr lesen.",pos:"erg"} ],
        why: "wenn-clause verb-final, then the main clause with <em>würde</em> at slot 2." },
      { id: 2302, type: "order", en: "Had I more money, I'd travel the world.",
        parts: [ {text:"Hätte",pos:"verb",label:"Verb zuerst"}, {text:"ich",pos:"subj"}, {text:"mehr Geld,",pos:"akk"}, {text:"würde",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"eine Weltreise",pos:"akk"}, {text:"machen.",pos:"verb",label:"ENDE"} ],
        why: "With <em>wenn</em> dropped, <em>hätte</em> opens the clause — the main clause is unaffected." },
      { id: 2303, type: "fix", wrong: "Wenn ich du wäre, ich würde den Kurs machen.", correct: "Wenn ich du wäre, würde ich den Kurs machen.", badIndex: 5,
        why: "The wenn-clause is position 1, so <em>würde</em> must be element 2." },
      { id: 2304, type: "order", en: "I could help you with the application.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"könnte",pos:"verb",label:"Pos 2"}, {text:"dir",pos:"dativ"}, {text:"bei der Bewerbung",pos:"erg"}, {text:"helfen.",pos:"verb",label:"ENDE"} ],
        why: "<em>könnte</em> has its own Konjunktiv form — no <em>würde</em> needed." },
      { id: 2305, type: "order", en: "In your place I'd talk to the teacher.",
        parts: [ {text:"An deiner Stelle",pos:"erg",label:"Pos 1"}, {text:"würde",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"mit dem Lehrer",pos:"erg"}, {text:"sprechen.",pos:"verb",label:"ENDE"} ],
        why: "Fronted phrase → inversion, and <em>würde … sprechen</em> forms the bracket." },
      { id: 2306, type: "fix", wrong: "Wenn ich das gewusst hätte, ich wäre nicht gekommen.", correct: "Wenn ich das gewusst hätte, wäre ich nicht gekommen.", badIndex: 6,
        why: "Past irrealis, same rule: the fronted clause is slot 1, so <em>wäre</em> is slot 2." },
      { id: 2307, type: "order", en: "It would be nice if you could come along.",
        parts: [ {text:"Es",pos:"subj"}, {text:"wäre",pos:"verb",label:"Pos 2"}, {text:"schön,",pos:"erg"}, {text:"wenn",pos:"conj",label:"Konj."}, {text:"du",pos:"subj"}, {text:"mitkommen",pos:"verb"}, {text:"könntest.",pos:"verb",label:"ENDE"} ],
        why: "The conjugated <em>könntest</em> closes the Nebensatz, after the infinitive." },
      { id: 2308, type: "order", en: "I should have got up earlier yesterday.",
        parts: [ {text:"Ich",pos:"subj"}, {text:"hätte",pos:"verb",label:"Pos 2"}, {text:"gestern",pos:"temp",label:"Te"}, {text:"früher",pos:"manner",label:"Mo"}, {text:"aufstehen",pos:"verb"}, {text:"sollen.",pos:"verb",label:"ENDE"} ],
        why: "Double infinitive: <em>aufstehen sollen</em> closes the bracket, in that order." },
      { id: 2309, type: "fix", wrong: "Würde ich mehr Zeit haben, ich würde mehr üben.", correct: "Würde ich mehr Zeit haben, würde ich mehr üben.", badIndex: 6,
        why: "The fronted conditional clause fills slot 1 — the main clause verb comes next." },
      { id: 2310, type: "order", en: "Without your help I wouldn't have passed the exam.",
        parts: [ {text:"Ohne deine Hilfe",pos:"erg",label:"Pos 1"}, {text:"hätte",pos:"verb",label:"Pos 2"}, {text:"ich",pos:"subj"}, {text:"die Prüfung",pos:"akk"}, {text:"nicht",pos:"erg"}, {text:"bestanden.",pos:"verb",label:"ENDE"} ],
        why: "An <em>ohne</em>-phrase can replace the whole wenn-clause in position 1." },
      { id: 2311, type: "order", en: "If the course were cheaper, more people would take part.",
        parts: [ {text:"Wenn",pos:"conj",label:"Konj."}, {text:"der Kurs",pos:"subj"}, {text:"billiger",pos:"erg"}, {text:"wäre,",pos:"verb",label:"ENDE"}, {text:"würden",pos:"verb",label:"Pos 2"}, {text:"mehr Leute",pos:"subj"}, {text:"teilnehmen.",pos:"verb",label:"ENDE"} ],
        why: "<em>wäre</em> ends the sub-clause; <em>würden … teilnehmen</em> brackets the main clause." },
      { id: 2312, type: "fix", wrong: "Könntest du bitte mir helfen?", correct: "Könntest du mir bitte helfen?", badIndex: 2,
        why: "The pronoun <em>mir</em> sits at the front of the middle field, ahead of <em>bitte</em>." },
    ],
  },

  // ---------------------------------------------------------- 14. Paare
  {
    id: "paare",
    label: "Zweiteilige Konnektoren — je … desto",
    cefr: "B2",
    color: "#fb7185",
    rule: {
      headline: "Two-part connectors each set their own word order — and <em>je … desto</em> uses two different ones in one sentence.",
      diagram: [
        { text: "Je mehr",   label: "je + Komparativ", pos: "conj" },
        { text: "ich lerne,", label: "VERB — ENDE", pos: "verb" },
        { text: "desto sicherer", label: "desto + Komparativ — Pos 1", pos: "conj" },
        { text: "werde",     label: "Pos 2 — VERB", pos: "verb" },
        { text: "ich.",      label: "Subjekt", pos: "subj" },
      ],
      points: [
        "The <em>je</em>-clause is a Nebensatz → verb at the end. The <em>desto</em>-clause is a main clause → verb second.",
        "The comparative glues to je and desto: <em>je mehr</em>, <em>desto besser</em>.",
        "<em>weder … noch</em> and <em>zwar</em> and <em>nicht nur</em> at position 1 all trigger inversion.",
        "<em>entweder … oder</em> and <em>sowohl … als auch</em> leave the order alone.",
      ],
      examples: [
        { de: "Je mehr ich lerne, desto sicherer werde ich.", en: "The more I study, the more confident I get." },
        { de: "Der Kurs ist zwar teuer, aber er lohnt sich.", en: "The course is expensive, true, but it's worth it." },
        { de: "Weder habe ich Zeit noch Geld.", en: "I have neither time nor money." },
      ],
      contrast: {
        a: "Je mehr ich lerne, desto sicherer werde ich.",
        b: "Ich werde sicherer, je mehr ich lerne.",
        note: "The je-clause is verb-final wherever it stands — only the desto-half needs slot 1.",
      },
    },
    items: [
      { id: 2401, type: "order", en: "The more I study, the more confident I get.",
        parts: [ {text:"Je",pos:"conj",label:"je"}, {text:"mehr",pos:"erg",label:"Komparativ"}, {text:"ich",pos:"subj"}, {text:"lerne,",pos:"verb",label:"ENDE"}, {text:"desto",pos:"conj",label:"desto"}, {text:"sicherer",pos:"erg",label:"Komparativ"}, {text:"werde",pos:"verb",label:"Pos 2"}, {text:"ich.",pos:"subj"} ],
        why: "je-clause verb-final, desto-clause verb-second." },
      { id: 2402, type: "order", en: "Either we go to the cinema or we stay at home.",
        parts: [ {text:"Entweder",pos:"conj",label:"Teil 1"}, {text:"wir",pos:"subj"}, {text:"gehen",pos:"verb",label:"Pos 2"}, {text:"ins Kino,",pos:"local"}, {text:"oder",pos:"conj",label:"Teil 2"}, {text:"wir",pos:"subj"}, {text:"bleiben",pos:"verb",label:"Pos 2"}, {text:"zu Hause.",pos:"local"} ],
        why: "<em>entweder … oder</em> may leave both clauses in plain subject-verb order." },
      { id: 2403, type: "fix", wrong: "Je länger ich in Deutschland wohne, desto ich verstehe mehr.", correct: "Je länger ich in Deutschland wohne, desto mehr verstehe ich.", badIndex: 7,
        why: "The comparative belongs directly after <em>desto</em>, and then the verb takes slot 2." },
      { id: 2404, type: "order", en: "The course is expensive, true, but it's worth it.",
        parts: [ {text:"Der Kurs",pos:"subj"}, {text:"ist",pos:"verb",label:"Pos 2"}, {text:"zwar",pos:"conj",label:"Teil 1"}, {text:"teuer,",pos:"erg"}, {text:"aber",pos:"conj",label:"Teil 2 — Pos 0"}, {text:"er",pos:"subj"}, {text:"lohnt",pos:"verb",label:"Pos 2"}, {text:"sich.",pos:"erg"} ],
        why: "Inside the middle field <em>zwar</em> changes nothing; <em>aber</em> stays position 0." },
      { id: 2405, type: "order", en: "She speaks not only German but also French.",
        parts: [ {text:"Sie",pos:"subj"}, {text:"spricht",pos:"verb",label:"Pos 2"}, {text:"nicht nur",pos:"conj",label:"Teil 1"}, {text:"Deutsch,",pos:"akk"}, {text:"sondern auch",pos:"conj",label:"Teil 2"}, {text:"Französisch.",pos:"akk"} ],
        why: "In the middle field the pair simply frames the two objects." },
      { id: 2406, type: "fix", wrong: "Weder ich habe Zeit noch Geld.", correct: "Weder habe ich Zeit noch Geld.", badIndex: 1,
        why: "<em>weder</em> at position 1 pushes the verb to slot 2 and the subject behind it." },
      { id: 2407, type: "order", en: "Both my sister and my brother learn German.",
        parts: [ {text:"Sowohl",pos:"conj",label:"Teil 1"}, {text:"meine Schwester",pos:"subj"}, {text:"als auch",pos:"conj",label:"Teil 2"}, {text:"mein Bruder",pos:"subj"}, {text:"lernen",pos:"verb",label:"Pos 2"}, {text:"Deutsch.",pos:"akk"} ],
        why: "<em>sowohl … als auch</em> builds one plural subject — still a single position-1 element." },
      { id: 2408, type: "order", en: "The sooner you start, the better your chances are.",
        parts: [ {text:"Je",pos:"conj",label:"je"}, {text:"früher",pos:"erg",label:"Komparativ"}, {text:"du",pos:"subj"}, {text:"anfängst,",pos:"verb",label:"ENDE"}, {text:"desto",pos:"conj",label:"desto"}, {text:"besser",pos:"erg",label:"Komparativ"}, {text:"sind",pos:"verb",label:"Pos 2"}, {text:"deine Chancen.",pos:"subj"} ],
        why: "Separable <em>anfangen</em> re-merges at the end of the je-clause." },
      { id: 2409, type: "fix", wrong: "Zwar der Kurs ist anstrengend, aber er macht Spaß.", correct: "Zwar ist der Kurs anstrengend, aber er macht Spaß.", badIndex: 3,
        why: "At position 1 <em>zwar</em> forces inversion — <em>ist</em> must be element 2." },
      { id: 2410, type: "order", en: "Either you study now or you fail.",
        parts: [ {text:"Entweder",pos:"conj",label:"Teil 1"}, {text:"du",pos:"subj"}, {text:"lernst",pos:"verb",label:"Pos 2"}, {text:"jetzt,",pos:"temp"}, {text:"oder",pos:"conj",label:"Teil 2 — Pos 0"}, {text:"du",pos:"subj"}, {text:"fällst",pos:"verb",label:"Pos 2"}, {text:"durch.",pos:"verb",label:"Präfix"} ],
        why: "Both halves are plain main clauses; <em>durchfallen</em> splits as usual." },
      { id: 2411, type: "fix", wrong: "Nicht nur er spricht Deutsch, sondern auch Spanisch.", correct: "Nicht nur spricht er Deutsch, sondern auch Spanisch.", badIndex: 2,
        why: "<em>nicht nur</em> at position 1 triggers inversion, exactly like <em>weder</em>." },
      { id: 2412, type: "order", en: "The more you practise, the easier it gets.",
        parts: [ {text:"Je",pos:"conj",label:"je"}, {text:"mehr",pos:"erg",label:"Komparativ"}, {text:"man",pos:"subj"}, {text:"übt,",pos:"verb",label:"ENDE"}, {text:"desto",pos:"conj",label:"desto"}, {text:"leichter",pos:"erg",label:"Komparativ"}, {text:"fällt",pos:"verb",label:"Pos 2"}, {text:"es",pos:"subj"}, {text:"einem.",pos:"dativ"} ],
        why: "Same two-order pattern, with an impersonal <em>man … einem</em>." },
    ],
  },

];
