// Talk Box game card data — 4 categories × 15 cards = 60 total
const TALKBOX_CARDS = {
  alltag: {
    label: "Alltag",
    labelEn: "Daily Life",
    color: "#f59e0b",
    cards: [
      { id: 101, de: "Beschreib deinen typischen Morgen.", en: "Describe your typical morning.", level: "a2" },
      { id: 102, de: "Was machst du normalerweise nach der Uni?", en: "What do you usually do after university?", level: "a2" },
      { id: 103, de: "Wie kommst du jeden Tag zur Uni?", en: "How do you get to university every day?", level: "a2" },
      { id: 104, de: "Was hast du heute zum Frühstück gegessen?", en: "What did you eat for breakfast today?", level: "a1" },
      { id: 105, de: "Beschreib dein Zimmer oder deine Wohnung.", en: "Describe your room or apartment.", level: "a2" },
      { id: 106, de: "Wie sieht dein typischer Abend aus?", en: "What does your typical evening look like?", level: "a2" },
      { id: 107, de: "Was kaufst du normalerweise ein?", en: "What do you normally buy when you go shopping?", level: "a2" },
      { id: 108, de: "Beschreib deinen Lieblingsort in der Stadt.", en: "Describe your favourite place in the city.", level: "b1" },
      { id: 109, de: "Was machst du am Wochenende?", en: "What do you do at the weekend?", level: "a1" },
      { id: 110, de: "Wie bereitest du dich auf einen wichtigen Tag vor?", en: "How do you prepare for an important day?", level: "b1" },
      { id: 111, de: "Beschreib eine typische Mahlzeit, die du kochst.", en: "Describe a typical meal you cook.", level: "b1" },
      { id: 112, de: "Wie bleibst du fit und gesund?", en: "How do you stay fit and healthy?", level: "a2" },
      { id: 113, de: "Was machst du, wenn du dich müde oder gestresst fühlst?", en: "What do you do when you feel tired or stressed?", level: "b1" },
      { id: 114, de: "Beschreib deinen Lieblingsweg oder Spaziergang.", en: "Describe your favourite walk or route.", level: "b1" },
      { id: 115, de: "Was hörst du gerne? Erzähl mir von deiner Lieblingsmusik.", en: "What do you like to listen to? Tell me about your favourite music.", level: "a2" },
    ],
  },
  meinungen: {
    label: "Meinungen",
    labelEn: "Opinions",
    color: "#8b5cf6",
    cards: [
      { id: 201, de: "Was denkst du über soziale Medien?", en: "What do you think about social media?", level: "b1" },
      { id: 202, de: "Ist Lernen alleine oder in der Gruppe besser?", en: "Is learning alone or in a group better?", level: "b1" },
      { id: 203, de: "Was ist deiner Meinung nach das Wichtigste beim Sprachenlernen?", en: "What do you think is most important in language learning?", level: "b2" },
      { id: 204, de: "Glaubst du, dass man eine Sprache ohne Auslandsaufenthalt lernen kann?", en: "Do you think you can learn a language without living abroad?", level: "b1" },
      { id: 205, de: "Was hältst du von Fast Food?", en: "What do you think of fast food?", level: "a2" },
      { id: 206, de: "Sollte man täglich Sport treiben? Warum oder warum nicht?", en: "Should one exercise daily? Why or why not?", level: "b1" },
      { id: 207, de: "Welche Technologie findest du am nützlichsten im Alltag?", en: "Which technology do you find most useful in everyday life?", level: "b1" },
      { id: 208, de: "Was ist deiner Meinung nach die beste Art zu reisen?", en: "In your opinion, what is the best way to travel?", level: "b1" },
      { id: 209, de: "Ist es wichtig, mehrere Sprachen zu sprechen? Warum?", en: "Is it important to speak multiple languages? Why?", level: "b1" },
      { id: 210, de: "Was denkst du über das Bildungssystem in Deutschland?", en: "What do you think about the education system in Germany?", level: "b2" },
      { id: 211, de: "Sollte man in der Freizeit arbeiten oder entspannen?", en: "Should one work or relax in one's free time?", level: "b1" },
      { id: 212, de: "Was ist das Schwierigste am Leben in einem anderen Land?", en: "What is the hardest thing about living in another country?", level: "b2" },
      { id: 213, de: "Welche Qualitäten sind dir in einem Freund am wichtigsten?", en: "What qualities are most important to you in a friend?", level: "b1" },
      { id: 214, de: "Glaubst du, dass Filme und Serien beim Sprachenlernen helfen?", en: "Do you think films and series help with language learning?", level: "b1" },
      { id: 215, de: "Was würdest du in deiner Stadt verbessern, wenn du die Möglichkeit hättest?", en: "What would you improve in your city if you had the chance?", level: "b2" },
    ],
  },
  szenarien: {
    label: "Szenarien",
    labelEn: "Scenarios",
    color: "#ef4444",
    cards: [
      { id: 301, de: "Du bist in Berlin und hast deine Tasche verloren. Was machst du?", en: "You are in Berlin and have lost your bag. What do you do?", level: "b1" },
      { id: 302, de: "Du hast Hunger, aber der Supermarkt ist zu. Wie löst du das Problem?", en: "You are hungry but the supermarket is closed. How do you solve the problem?", level: "a2" },
      { id: 303, de: "Du bist beim Arzt und fühlst dich nicht wohl. Erkläre deine Symptome.", en: "You are at the doctor and don't feel well. Explain your symptoms.", level: "b1" },
      { id: 304, de: "Du bestellst in einem Restaurant, aber das Essen ist nicht das, was du wolltest. Was sagst du?", en: "You order in a restaurant but the food is not what you wanted. What do you say?", level: "a2" },
      { id: 305, de: "Du bist im Supermarkt und brauchst Hilfe, etwas zu finden. Übe das Gespräch.", en: "You are in a supermarket and need help finding something. Practise the conversation.", level: "a2" },
      { id: 306, de: "Du bist neu in deiner Wohngemeinschaft und stellst dich vor.", en: "You are new to your shared flat and are introducing yourself.", level: "a2" },
      { id: 307, de: "Du rufst bei deiner Universität an, um eine Frage zu stellen. Was sagst du?", en: "You call your university to ask a question. What do you say?", level: "b1" },
      { id: 308, de: "Jemand fragt dich nach dem Weg zur nächsten U-Bahn-Station.", en: "Someone asks you for directions to the nearest underground station.", level: "a2" },
      { id: 309, de: "Du triffst jemanden zum ersten Mal auf einer Party. Führe ein Gespräch auf Deutsch.", en: "You meet someone for the first time at a party. Have a conversation in German.", level: "b1" },
      { id: 310, de: "Du möchtest ein gekauftes Produkt zurückgeben. Erkläre das Problem.", en: "You want to return a product you bought. Explain the problem.", level: "b1" },
      { id: 311, de: "Du bist im Zug und hast dein Ticket vergessen. Was sagst du dem Schaffner?", en: "You are on the train and have forgotten your ticket. What do you say to the conductor?", level: "b1" },
      { id: 312, de: "Du möchtest in einem Café wlan-Passwort und eine Empfehlung vom Kellner.", en: "You want the wifi password and a recommendation from the waiter in a café.", level: "a2" },
      { id: 313, de: "Dein Nachbar macht nachts Lärm. Du klingelst und sprichst mit ihm.", en: "Your neighbour is making noise at night. You ring the bell and talk to him.", level: "b1" },
      { id: 314, de: "Du möchtest an der Uni ein Fach wechseln. Erkläre deinem Studienberater warum.", en: "You want to change your subject at university. Explain to your academic advisor why.", level: "b2" },
      { id: 315, de: "Du bist zu einem deutschen Abendessen eingeladen. Erkläre, was du magst und was nicht.", en: "You are invited to a German dinner. Explain what you like and dislike.", level: "a2" },
    ],
  },
  uni_leben: {
    label: "Uni-Leben",
    labelEn: "Uni Life",
    color: "#10b981",
    cards: [
      { id: 401, de: "Beschreib deinen Stundenplan diese Woche.", en: "Describe your timetable this week.", level: "a2" },
      { id: 402, de: "Was ist das Schwierigste an deinem Studium?", en: "What is the most difficult thing about your studies?", level: "b1" },
      { id: 403, de: "Wie bereitest du dich auf eine Prüfung vor?", en: "How do you prepare for an exam?", level: "b1" },
      { id: 404, de: "Beschreib deinen Lieblingsprofessor oder deine Lieblingsprofessorin.", en: "Describe your favourite professor.", level: "b1" },
      { id: 405, de: "Was machst du in der Mittagspause an der Uni?", en: "What do you do during your lunch break at university?", level: "a2" },
      { id: 406, de: "Erkläre ein Konzept aus einem deiner Kurse auf Deutsch.", en: "Explain a concept from one of your courses in German.", level: "b2" },
      { id: 407, de: "Was ist der beste Ort zum Lernen auf dem Campus?", en: "What is the best place to study on campus?", level: "a2" },
      { id: 408, de: "Wie arbeitest du in einer Gruppe? Welche Rolle nimmst du ein?", en: "How do you work in a group? What role do you take?", level: "b1" },
      { id: 409, de: "Beschreib eine interessante Vorlesung, die du besucht hast.", en: "Describe an interesting lecture you attended.", level: "b1" },
      { id: 410, de: "Was machst du nach einer schwierigen Prüfung?", en: "What do you do after a difficult exam?", level: "a2" },
      { id: 411, de: "Hast du schon eine wichtige Deadline verpasst? Was ist passiert?", en: "Have you ever missed an important deadline? What happened?", level: "b1" },
      { id: 412, de: "Wie bist du zu deinem Studienfach gekommen? Warum hast du es gewählt?", en: "How did you come to your subject? Why did you choose it?", level: "b1" },
      { id: 413, de: "Was würdest du an deiner Uni verbessern, wenn du könntest?", en: "What would you improve at your university if you could?", level: "b1" },
      { id: 414, de: "Beschreib den lustigsten oder schönsten Moment an der Uni.", en: "Describe the funniest or best moment at university.", level: "b1" },
      { id: 415, de: "Wie findest du das Leben als Student in Deutschland?", en: "What do you think of life as a student in Germany?", level: "b1" },
    ],
  },
};
